package discord_js;

@:jsRequire("discord.js", "BitField") extern class BitField<S> {
	function new(?bits:ts.AnyOf4<Float, RecursiveReadonlyArray<ts.AnyOf3<Float, { var bitfield : Float; dynamic function add(bits:haxe.extern.Rest<BitFieldResolvable<S>>):BitField<S>; dynamic function any(bit:BitFieldResolvable<S>):Bool; dynamic function equals(bit:BitFieldResolvable<S>):Bool; dynamic function freeze():{ var bitfield : Float; dynamic function add(bits:haxe.extern.Rest<BitFieldResolvable<S>>):BitField<S>; dynamic function any(bit:BitFieldResolvable<S>):Bool; dynamic function equals(bit:BitFieldResolvable<S>):Bool; dynamic function freeze():{ var bitfield : Float; dynamic function add(bits:haxe.extern.Rest<BitFieldResolvable<S>>):BitField<S>; dynamic function any(bit:BitFieldResolvable<S>):Bool; dynamic function equals(bit:BitFieldResolvable<S>):Bool; dynamic function freeze():{ var bitfield : Float; dynamic function add(bits:haxe.extern.Rest<BitFieldResolvable<S>>):BitField<S>; dynamic function any(bit:BitFieldResolvable<S>):Bool; dynamic function equals(bit:BitFieldResolvable<S>):Bool; dynamic function freeze():{ var bitfield : Float; dynamic function add(bits:haxe.extern.Rest<BitFieldResolvable<S>>):BitField<S>; dynamic function any(bit:BitFieldResolvable<S>):Bool; dynamic function equals(bit:BitFieldResolvable<S>):Bool; dynamic function freeze():{ var bitfield : Float; dynamic function add(bits:haxe.extern.Rest<BitFieldResolvable<S>>):BitField<S>; dynamic function any(bit:BitFieldResolvable<S>):Bool; dynamic function equals(bit:BitFieldResolvable<S>):Bool; dynamic function freeze():{ var bitfield : Float; dynamic function add(bits:haxe.extern.Rest<BitFieldResolvable<S>>):BitField<S>; dynamic function any(bit:BitFieldResolvable<S>):Bool; dynamic function equals(bit:BitFieldResolvable<S>):Bool; dynamic function freeze():{ var bitfield : Float; dynamic function add(bits:haxe.extern.Rest<BitFieldResolvable<S>>):BitField<S>; dynamic function any(bit:BitFieldResolvable<S>):Bool; dynamic function equals(bit:BitFieldResolvable<S>):Bool; dynamic function freeze():{ var bitfield : Float; dynamic function add(bits:haxe.extern.Rest<BitFieldResolvable<S>>):BitField<S>; dynamic function any(bit:BitFieldResolvable<S>):Bool; dynamic function equals(bit:BitFieldResolvable<S>):Bool; dynamic function freeze():{ var bitfield : Float; dynamic function add(bits:haxe.extern.Rest<BitFieldResolvable<S>>):BitField<S>; dynamic function any(bit:BitFieldResolvable<S>):Bool; dynamic function equals(bit:BitFieldResolvable<S>):Bool; dynamic function freeze():{ var bitfield : Float; dynamic function add(bits:haxe.extern.Rest<BitFieldResolvable<S>>):BitField<S>; dynamic function any(bit:BitFieldResolvable<S>):Bool; dynamic function equals(bit:BitFieldResolvable<S>):Bool; dynamic function freeze():{ var bitfield : Float; dynamic function add(bits:haxe.extern.Rest<BitFieldResolvable<S>>):BitField<S>; dynamic function any(bit:BitFieldResolvable<S>):Bool; dynamic function equals(bit:BitFieldResolvable<S>):Bool; dynamic function freeze():{ var bitfield : Float; dynamic function add(bits:haxe.extern.Rest<BitFieldResolvable<S>>):BitField<S>; dynamic function any(bit:BitFieldResolvable<S>):Bool; dynamic function equals(bit:BitFieldResolvable<S>):Bool; dynamic function freeze():{ var bitfield : Float; dynamic function add(bits:haxe.extern.Rest<BitFieldResolvable<S>>):BitField<S>; dynamic function any(bit:BitFieldResolvable<S>):Bool; dynamic function equals(bit:BitFieldResolvable<S>):Bool; dynamic function freeze():{ var bitfield : Float; dynamic function add(bits:haxe.extern.Rest<BitFieldResolvable<S>>):BitField<S>; dynamic function any(bit:BitFieldResolvable<S>):Bool; dynamic function equals(bit:BitFieldResolvable<S>):Bool; dynamic function freeze():{ var bitfield : Float; dynamic function add(bits:haxe.extern.Rest<BitFieldResolvable<S>>):BitField<S>; dynamic function any(bit:BitFieldResolvable<S>):Bool; dynamic function equals(bit:BitFieldResolvable<S>):Bool; dynamic function freeze():{ var bitfield : Float; dynamic function add(bits:haxe.extern.Rest<BitFieldResolvable<S>>):BitField<S>; dynamic function any(bit:BitFieldResolvable<S>):Bool; dynamic function equals(bit:BitFieldResolvable<S>):Bool; dynamic function freeze():{ var bitfield : Float; dynamic function add(bits:haxe.extern.Rest<BitFieldResolvable<S>>):BitField<S>; dynamic function any(bit:BitFieldResolvable<S>):Bool; dynamic function equals(bit:BitFieldResolvable<S>):Bool; dynamic function freeze():{ var bitfield : Float; dynamic function add(bits:haxe.extern.Rest<BitFieldResolvable<S>>):BitField<S>; dynamic function any(bit:BitFieldResolvable<S>):Bool; dynamic function equals(bit:BitFieldResolvable<S>):Bool; dynamic function freeze():{ var bitfield : Float; dynamic function add(bits:haxe.extern.Rest<BitFieldResolvable<Dynamic>>):BitField<S>; dynamic function any(bit:BitFieldResolvable<S>):Bool; dynamic function equals(bit:BitFieldResolvable<S>):Bool; dynamic function freeze():{ var bitfield : Float; dynamic function add(bits:haxe.extern.Rest<Any>):BitField<S>; dynamic function any(bit:BitFieldResolvable<Dynamic>):Bool; dynamic function equals(bit:BitFieldResolvable<Dynamic>):Bool; dynamic function freeze():{ var bitfield : Dynamic; dynamic function add(bits:haxe.extern.Rest<Any>):Dynamic; dynamic function any(bit:Dynamic):Dynamic; dynamic function equals(bit:Dynamic):Dynamic; dynamic function freeze():Dynamic; dynamic function has(bit:Dynamic):Dynamic; dynamic function missing(bits:Dynamic, hasParam:haxe.extern.Rest<Any>):Dynamic; dynamic function remove(bits:haxe.extern.Rest<Any>):Dynamic; dynamic function serialize(hasParam:haxe.extern.Rest<Any>):Dynamic; dynamic function toArray(hasParam:haxe.extern.Rest<Any>):Dynamic; dynamic function toJSON():Dynamic; dynamic function valueOf():Dynamic; }; dynamic function has(bit:BitFieldResolvable<Dynamic>):Bool; dynamic function missing(bits:BitFieldResolvable<Dynamic>, hasParam:haxe.extern.Rest<Any>):Dynamic<Dynamic>; dynamic function remove(bits:haxe.extern.Rest<Any>):BitField<S>; dynamic function serialize(hasParam:haxe.extern.Rest<Any>):{ }; dynamic function toArray(hasParam:haxe.extern.Rest<Any>):Dynamic<Dynamic>; dynamic function toJSON():Float; dynamic function valueOf():Float; }; dynamic function has(bit:BitFieldResolvable<S>):Bool; dynamic function missing(bits:BitFieldResolvable<S>, hasParam:haxe.extern.Rest<Any>):Array<S>; dynamic function remove(bits:haxe.extern.Rest<BitFieldResolvable<Dynamic>>):BitField<S>; dynamic function serialize(hasParam:haxe.extern.Rest<Any>):{ }; dynamic function toArray(hasParam:haxe.extern.Rest<Any>):Array<S>; dynamic function toJSON():Float; dynamic function valueOf():Float; }; dynamic function has(bit:BitFieldResolvable<S>):Bool; dynamic function missing(bits:BitFieldResolvable<S>, hasParam:haxe.extern.Rest<Any>):Array<S>; dynamic function remove(bits:haxe.extern.Rest<BitFieldResolvable<S>>):BitField<S>; dynamic function serialize(hasParam:haxe.extern.Rest<Any>):{ }; dynamic function toArray(hasParam:haxe.extern.Rest<Any>):Array<S>; dynamic function toJSON():Float; dynamic function valueOf():Float; }; dynamic function has(bit:BitFieldResolvable<S>):Bool; dynamic function missing(bits:BitFieldResolvable<S>, hasParam:haxe.extern.Rest<Any>):Array<S>; dynamic function remove(bits:haxe.extern.Rest<BitFieldResolvable<S>>):BitField<S>; dynamic function serialize(hasParam:haxe.extern.Rest<Any>):{ }; dynamic function toArray(hasParam:haxe.extern.Rest<Any>):Array<S>; dynamic function toJSON():Float; dynamic function valueOf():Float; }; dynamic function has(bit:BitFieldResolvable<S>):Bool; dynamic function missing(bits:BitFieldResolvable<S>, hasParam:haxe.extern.Rest<Any>):Array<S>; dynamic function remove(bits:haxe.extern.Rest<BitFieldResolvable<S>>):BitField<S>; dynamic function serialize(hasParam:haxe.extern.Rest<Any>):{ }; dynamic function toArray(hasParam:haxe.extern.Rest<Any>):Array<S>; dynamic function toJSON():Float; dynamic function valueOf():Float; }; dynamic function has(bit:BitFieldResolvable<S>):Bool; dynamic function missing(bits:BitFieldResolvable<S>, hasParam:haxe.extern.Rest<Any>):Array<S>; dynamic function remove(bits:haxe.extern.Rest<BitFieldResolvable<S>>):BitField<S>; dynamic function serialize(hasParam:haxe.extern.Rest<Any>):{ }; dynamic function toArray(hasParam:haxe.extern.Rest<Any>):Array<S>; dynamic function toJSON():Float; dynamic function valueOf():Float; }; dynamic function has(bit:BitFieldResolvable<S>):Bool; dynamic function missing(bits:BitFieldResolvable<S>, hasParam:haxe.extern.Rest<Any>):Array<S>; dynamic function remove(bits:haxe.extern.Rest<BitFieldResolvable<S>>):BitField<S>; dynamic function serialize(hasParam:haxe.extern.Rest<Any>):{ }; dynamic function toArray(hasParam:haxe.extern.Rest<Any>):Array<S>; dynamic function toJSON():Float; dynamic function valueOf():Float; }; dynamic function has(bit:BitFieldResolvable<S>):Bool; dynamic function missing(bits:BitFieldResolvable<S>, hasParam:haxe.extern.Rest<Any>):Array<S>; dynamic function remove(bits:haxe.extern.Rest<BitFieldResolvable<S>>):BitField<S>; dynamic function serialize(hasParam:haxe.extern.Rest<Any>):{ }; dynamic function toArray(hasParam:haxe.extern.Rest<Any>):Array<S>; dynamic function toJSON():Float; dynamic function valueOf():Float; }; dynamic function has(bit:BitFieldResolvable<S>):Bool; dynamic function missing(bits:BitFieldResolvable<S>, hasParam:haxe.extern.Rest<Any>):Array<S>; dynamic function remove(bits:haxe.extern.Rest<BitFieldResolvable<S>>):BitField<S>; dynamic function serialize(hasParam:haxe.extern.Rest<Any>):{ }; dynamic function toArray(hasParam:haxe.extern.Rest<Any>):Array<S>; dynamic function toJSON():Float; dynamic function valueOf():Float; }; dynamic function has(bit:BitFieldResolvable<S>):Bool; dynamic function missing(bits:BitFieldResolvable<S>, hasParam:haxe.extern.Rest<Any>):Array<S>; dynamic function remove(bits:haxe.extern.Rest<BitFieldResolvable<S>>):BitField<S>; dynamic function serialize(hasParam:haxe.extern.Rest<Any>):{ }; dynamic function toArray(hasParam:haxe.extern.Rest<Any>):Array<S>; dynamic function toJSON():Float; dynamic function valueOf():Float; }; dynamic function has(bit:BitFieldResolvable<S>):Bool; dynamic function missing(bits:BitFieldResolvable<S>, hasParam:haxe.extern.Rest<Any>):Array<S>; dynamic function remove(bits:haxe.extern.Rest<BitFieldResolvable<S>>):BitField<S>; dynamic function serialize(hasParam:haxe.extern.Rest<Any>):{ }; dynamic function toArray(hasParam:haxe.extern.Rest<Any>):Array<S>; dynamic function toJSON():Float; dynamic function valueOf():Float; }; dynamic function has(bit:BitFieldResolvable<S>):Bool; dynamic function missing(bits:BitFieldResolvable<S>, hasParam:haxe.extern.Rest<Any>):Array<S>; dynamic function remove(bits:haxe.extern.Rest<BitFieldResolvable<S>>):BitField<S>; dynamic function serialize(hasParam:haxe.extern.Rest<Any>):{ }; dynamic function toArray(hasParam:haxe.extern.Rest<Any>):Array<S>; dynamic function toJSON():Float; dynamic function valueOf():Float; }; dynamic function has(bit:BitFieldResolvable<S>):Bool; dynamic function missing(bits:BitFieldResolvable<S>, hasParam:haxe.extern.Rest<Any>):Array<S>; dynamic function remove(bits:haxe.extern.Rest<BitFieldResolvable<S>>):BitField<S>; dynamic function serialize(hasParam:haxe.extern.Rest<Any>):{ }; dynamic function toArray(hasParam:haxe.extern.Rest<Any>):Array<S>; dynamic function toJSON():Float; dynamic function valueOf():Float; }; dynamic function has(bit:BitFieldResolvable<S>):Bool; dynamic function missing(bits:BitFieldResolvable<S>, hasParam:haxe.extern.Rest<Any>):Array<S>; dynamic function remove(bits:haxe.extern.Rest<BitFieldResolvable<S>>):BitField<S>; dynamic function serialize(hasParam:haxe.extern.Rest<Any>):{ }; dynamic function toArray(hasParam:haxe.extern.Rest<Any>):Array<S>; dynamic function toJSON():Float; dynamic function valueOf():Float; }; dynamic function has(bit:BitFieldResolvable<S>):Bool; dynamic function missing(bits:BitFieldResolvable<S>, hasParam:haxe.extern.Rest<Any>):Array<S>; dynamic function remove(bits:haxe.extern.Rest<BitFieldResolvable<S>>):BitField<S>; dynamic function serialize(hasParam:haxe.extern.Rest<Any>):{ }; dynamic function toArray(hasParam:haxe.extern.Rest<Any>):Array<S>; dynamic function toJSON():Float; dynamic function valueOf():Float; }; dynamic function has(bit:BitFieldResolvable<S>):Bool; dynamic function missing(bits:BitFieldResolvable<S>, hasParam:haxe.extern.Rest<Any>):Array<S>; dynamic function remove(bits:haxe.extern.Rest<BitFieldResolvable<S>>):BitField<S>; dynamic function serialize(hasParam:haxe.extern.Rest<Any>):{ }; dynamic function toArray(hasParam:haxe.extern.Rest<Any>):Array<S>; dynamic function toJSON():Float; dynamic function valueOf():Float; }; dynamic function has(bit:BitFieldResolvable<S>):Bool; dynamic function missing(bits:BitFieldResolvable<S>, hasParam:haxe.extern.Rest<Any>):Array<S>; dynamic function remove(bits:haxe.extern.Rest<BitFieldResolvable<S>>):BitField<S>; dynamic function serialize(hasParam:haxe.extern.Rest<Any>):{ }; dynamic function toArray(hasParam:haxe.extern.Rest<Any>):Array<S>; dynamic function toJSON():Float; dynamic function valueOf():Float; }; dynamic function has(bit:BitFieldResolvable<S>):Bool; dynamic function missing(bits:BitFieldResolvable<S>, hasParam:haxe.extern.Rest<Any>):Array<S>; dynamic function remove(bits:haxe.extern.Rest<BitFieldResolvable<S>>):BitField<S>; dynamic function serialize(hasParam:haxe.extern.Rest<Any>):{ }; dynamic function toArray(hasParam:haxe.extern.Rest<Any>):Array<S>; dynamic function toJSON():Float; dynamic function valueOf():Float; }; dynamic function has(bit:BitFieldResolvable<S>):Bool; dynamic function missing(bits:BitFieldResolvable<S>, hasParam:haxe.extern.Rest<Any>):Array<S>; dynamic function remove(bits:haxe.extern.Rest<BitFieldResolvable<S>>):BitField<S>; dynamic function serialize(hasParam:haxe.extern.Rest<Any>):{ }; dynamic function toArray(hasParam:haxe.extern.Rest<Any>):Array<S>; dynamic function toJSON():Float; dynamic function valueOf():Float; }; dynamic function has(bit:BitFieldResolvable<S>):Bool; dynamic function missing(bits:BitFieldResolvable<S>, hasParam:haxe.extern.Rest<Any>):Array<S>; dynamic function remove(bits:haxe.extern.Rest<BitFieldResolvable<S>>):BitField<S>; dynamic function serialize(hasParam:haxe.extern.Rest<Any>):{ }; dynamic function toArray(hasParam:haxe.extern.Rest<Any>):Array<S>; dynamic function toJSON():Float; dynamic function valueOf():Float; }; dynamic function has(bit:BitFieldResolvable<S>):Bool; dynamic function missing(bits:BitFieldResolvable<S>, hasParam:haxe.extern.Rest<Any>):Array<S>; dynamic function remove(bits:haxe.extern.Rest<BitFieldResolvable<S>>):BitField<S>; dynamic function serialize(hasParam:haxe.extern.Rest<Any>):{ }; dynamic function toArray(hasParam:haxe.extern.Rest<Any>):Array<S>; dynamic function toJSON():Float; dynamic function valueOf():Float; }, S>>, { var bitfield : Float; dynamic function add(bits:haxe.extern.Rest<BitFieldResolvable<S>>):BitField<S>; dynamic function any(bit:BitFieldResolvable<S>):Bool; dynamic function equals(bit:BitFieldResolvable<S>):Bool; dynamic function freeze():{ var bitfield : Float; dynamic function add(bits:haxe.extern.Rest<BitFieldResolvable<S>>):BitField<S>; dynamic function any(bit:BitFieldResolvable<S>):Bool; dynamic function equals(bit:BitFieldResolvable<S>):Bool; dynamic function freeze():{ var bitfield : Float; dynamic function add(bits:haxe.extern.Rest<BitFieldResolvable<S>>):BitField<S>; dynamic function any(bit:BitFieldResolvable<S>):Bool; dynamic function equals(bit:BitFieldResolvable<S>):Bool; dynamic function freeze():{ var bitfield : Float; dynamic function add(bits:haxe.extern.Rest<BitFieldResolvable<S>>):BitField<S>; dynamic function any(bit:BitFieldResolvable<S>):Bool; dynamic function equals(bit:BitFieldResolvable<S>):Bool; dynamic function freeze():{ var bitfield : Float; dynamic function add(bits:haxe.extern.Rest<BitFieldResolvable<S>>):BitField<S>; dynamic function any(bit:BitFieldResolvable<S>):Bool; dynamic function equals(bit:BitFieldResolvable<S>):Bool; dynamic function freeze():{ var bitfield : Float; dynamic function add(bits:haxe.extern.Rest<BitFieldResolvable<S>>):BitField<S>; dynamic function any(bit:BitFieldResolvable<S>):Bool; dynamic function equals(bit:BitFieldResolvable<S>):Bool; dynamic function freeze():{ var bitfield : Float; dynamic function add(bits:haxe.extern.Rest<BitFieldResolvable<S>>):BitField<S>; dynamic function any(bit:BitFieldResolvable<S>):Bool; dynamic function equals(bit:BitFieldResolvable<S>):Bool; dynamic function freeze():{ var bitfield : Float; dynamic function add(bits:haxe.extern.Rest<BitFieldResolvable<S>>):BitField<S>; dynamic function any(bit:BitFieldResolvable<S>):Bool; dynamic function equals(bit:BitFieldResolvable<S>):Bool; dynamic function freeze():{ var bitfield : Float; dynamic function add(bits:haxe.extern.Rest<BitFieldResolvable<S>>):BitField<S>; dynamic function any(bit:BitFieldResolvable<S>):Bool; dynamic function equals(bit:BitFieldResolvable<S>):Bool; dynamic function freeze():{ var bitfield : Float; dynamic function add(bits:haxe.extern.Rest<BitFieldResolvable<S>>):BitField<S>; dynamic function any(bit:BitFieldResolvable<S>):Bool; dynamic function equals(bit:BitFieldResolvable<S>):Bool; dynamic function freeze():{ var bitfield : Float; dynamic function add(bits:haxe.extern.Rest<BitFieldResolvable<S>>):BitField<S>; dynamic function any(bit:BitFieldResolvable<S>):Bool; dynamic function equals(bit:BitFieldResolvable<S>):Bool; dynamic function freeze():{ var bitfield : Float; dynamic function add(bits:haxe.extern.Rest<BitFieldResolvable<S>>):BitField<S>; dynamic function any(bit:BitFieldResolvable<S>):Bool; dynamic function equals(bit:BitFieldResolvable<S>):Bool; dynamic function freeze():{ var bitfield : Float; dynamic function add(bits:haxe.extern.Rest<BitFieldResolvable<S>>):BitField<S>; dynamic function any(bit:BitFieldResolvable<S>):Bool; dynamic function equals(bit:BitFieldResolvable<S>):Bool; dynamic function freeze():{ var bitfield : Float; dynamic function add(bits:haxe.extern.Rest<BitFieldResolvable<S>>):BitField<S>; dynamic function any(bit:BitFieldResolvable<S>):Bool; dynamic function equals(bit:BitFieldResolvable<S>):Bool; dynamic function freeze():{ var bitfield : Float; dynamic function add(bits:haxe.extern.Rest<BitFieldResolvable<S>>):BitField<S>; dynamic function any(bit:BitFieldResolvable<S>):Bool; dynamic function equals(bit:BitFieldResolvable<S>):Bool; dynamic function freeze():{ var bitfield : Float; dynamic function add(bits:haxe.extern.Rest<BitFieldResolvable<S>>):BitField<S>; dynamic function any(bit:BitFieldResolvable<S>):Bool; dynamic function equals(bit:BitFieldResolvable<S>):Bool; dynamic function freeze():{ var bitfield : Float; dynamic function add(bits:haxe.extern.Rest<BitFieldResolvable<S>>):BitField<S>; dynamic function any(bit:BitFieldResolvable<S>):Bool; dynamic function equals(bit:BitFieldResolvable<S>):Bool; dynamic function freeze():{ var bitfield : Float; dynamic function add(bits:haxe.extern.Rest<BitFieldResolvable<S>>):BitField<S>; dynamic function any(bit:BitFieldResolvable<S>):Bool; dynamic function equals(bit:BitFieldResolvable<S>):Bool; dynamic function freeze():{ var bitfield : Float; dynamic function add(bits:haxe.extern.Rest<BitFieldResolvable<S>>):BitField<S>; dynamic function any(bit:BitFieldResolvable<S>):Bool; dynamic function equals(bit:BitFieldResolvable<S>):Bool; dynamic function freeze():{ var bitfield : Float; dynamic function add(bits:haxe.extern.Rest<BitFieldResolvable<S>>):BitField<S>; dynamic function any(bit:BitFieldResolvable<S>):Bool; dynamic function equals(bit:BitFieldResolvable<S>):Bool; dynamic function freeze():{ var bitfield : Float; dynamic function add(bits:haxe.extern.Rest<BitFieldResolvable<S>>):BitField<S>; dynamic function any(bit:BitFieldResolvable<S>):Bool; dynamic function equals(bit:BitFieldResolvable<S>):Bool; dynamic function freeze():{ var bitfield : Float; dynamic function add(bits:haxe.extern.Rest<BitFieldResolvable<Dynamic>>):BitField<S>; dynamic function any(bit:BitFieldResolvable<S>):Bool; dynamic function equals(bit:BitFieldResolvable<S>):Bool; dynamic function freeze():{ var bitfield : Float; dynamic function add(bits:haxe.extern.Rest<Any>):BitField<S>; dynamic function any(bit:BitFieldResolvable<Dynamic>):Bool; dynamic function equals(bit:BitFieldResolvable<Dynamic>):Bool; dynamic function freeze():{ var bitfield : Dynamic; dynamic function add(bits:haxe.extern.Rest<Any>):Dynamic; dynamic function any(bit:Dynamic):Dynamic; dynamic function equals(bit:Dynamic):Dynamic; dynamic function freeze():Dynamic; dynamic function has(bit:Dynamic):Dynamic; dynamic function missing(bits:Dynamic, hasParam:haxe.extern.Rest<Any>):Dynamic; dynamic function remove(bits:haxe.extern.Rest<Any>):Dynamic; dynamic function serialize(hasParam:haxe.extern.Rest<Any>):Dynamic; dynamic function toArray(hasParam:haxe.extern.Rest<Any>):Dynamic; dynamic function toJSON():Dynamic; dynamic function valueOf():Dynamic; }; dynamic function has(bit:BitFieldResolvable<Dynamic>):Bool; dynamic function missing(bits:BitFieldResolvable<Dynamic>, hasParam:haxe.extern.Rest<Any>):Dynamic<Dynamic>; dynamic function remove(bits:haxe.extern.Rest<Any>):BitField<S>; dynamic function serialize(hasParam:haxe.extern.Rest<Any>):{ }; dynamic function toArray(hasParam:haxe.extern.Rest<Any>):Dynamic<Dynamic>; dynamic function toJSON():Float; dynamic function valueOf():Float; }; dynamic function has(bit:BitFieldResolvable<S>):Bool; dynamic function missing(bits:BitFieldResolvable<S>, hasParam:haxe.extern.Rest<Any>):Array<S>; dynamic function remove(bits:haxe.extern.Rest<BitFieldResolvable<Dynamic>>):BitField<S>; dynamic function serialize(hasParam:haxe.extern.Rest<Any>):{ }; dynamic function toArray(hasParam:haxe.extern.Rest<Any>):Array<S>; dynamic function toJSON():Float; dynamic function valueOf():Float; }; dynamic function has(bit:BitFieldResolvable<S>):Bool; dynamic function missing(bits:BitFieldResolvable<S>, hasParam:haxe.extern.Rest<Any>):Array<S>; dynamic function remove(bits:haxe.extern.Rest<BitFieldResolvable<S>>):BitField<S>; dynamic function serialize(hasParam:haxe.extern.Rest<Any>):{ }; dynamic function toArray(hasParam:haxe.extern.Rest<Any>):Array<S>; dynamic function toJSON():Float; dynamic function valueOf():Float; }; dynamic function has(bit:BitFieldResolvable<S>):Bool; dynamic function missing(bits:BitFieldResolvable<S>, hasParam:haxe.extern.Rest<Any>):Array<S>; dynamic function remove(bits:haxe.extern.Rest<BitFieldResolvable<S>>):BitField<S>; dynamic function serialize(hasParam:haxe.extern.Rest<Any>):{ }; dynamic function toArray(hasParam:haxe.extern.Rest<Any>):Array<S>; dynamic function toJSON():Float; dynamic function valueOf():Float; }; dynamic function has(bit:BitFieldResolvable<S>):Bool; dynamic function missing(bits:BitFieldResolvable<S>, hasParam:haxe.extern.Rest<Any>):Array<S>; dynamic function remove(bits:haxe.extern.Rest<BitFieldResolvable<S>>):BitField<S>; dynamic function serialize(hasParam:haxe.extern.Rest<Any>):{ }; dynamic function toArray(hasParam:haxe.extern.Rest<Any>):Array<S>; dynamic function toJSON():Float; dynamic function valueOf():Float; }; dynamic function has(bit:BitFieldResolvable<S>):Bool; dynamic function missing(bits:BitFieldResolvable<S>, hasParam:haxe.extern.Rest<Any>):Array<S>; dynamic function remove(bits:haxe.extern.Rest<BitFieldResolvable<S>>):BitField<S>; dynamic function serialize(hasParam:haxe.extern.Rest<Any>):{ }; dynamic function toArray(hasParam:haxe.extern.Rest<Any>):Array<S>; dynamic function toJSON():Float; dynamic function valueOf():Float; }; dynamic function has(bit:BitFieldResolvable<S>):Bool; dynamic function missing(bits:BitFieldResolvable<S>, hasParam:haxe.extern.Rest<Any>):Array<S>; dynamic function remove(bits:haxe.extern.Rest<BitFieldResolvable<S>>):BitField<S>; dynamic function serialize(hasParam:haxe.extern.Rest<Any>):{ }; dynamic function toArray(hasParam:haxe.extern.Rest<Any>):Array<S>; dynamic function toJSON():Float; dynamic function valueOf():Float; }; dynamic function has(bit:BitFieldResolvable<S>):Bool; dynamic function missing(bits:BitFieldResolvable<S>, hasParam:haxe.extern.Rest<Any>):Array<S>; dynamic function remove(bits:haxe.extern.Rest<BitFieldResolvable<S>>):BitField<S>; dynamic function serialize(hasParam:haxe.extern.Rest<Any>):{ }; dynamic function toArray(hasParam:haxe.extern.Rest<Any>):Array<S>; dynamic function toJSON():Float; dynamic function valueOf():Float; }; dynamic function has(bit:BitFieldResolvable<S>):Bool; dynamic function missing(bits:BitFieldResolvable<S>, hasParam:haxe.extern.Rest<Any>):Array<S>; dynamic function remove(bits:haxe.extern.Rest<BitFieldResolvable<S>>):BitField<S>; dynamic function serialize(hasParam:haxe.extern.Rest<Any>):{ }; dynamic function toArray(hasParam:haxe.extern.Rest<Any>):Array<S>; dynamic function toJSON():Float; dynamic function valueOf():Float; }; dynamic function has(bit:BitFieldResolvable<S>):Bool; dynamic function missing(bits:BitFieldResolvable<S>, hasParam:haxe.extern.Rest<Any>):Array<S>; dynamic function remove(bits:haxe.extern.Rest<BitFieldResolvable<S>>):BitField<S>; dynamic function serialize(hasParam:haxe.extern.Rest<Any>):{ }; dynamic function toArray(hasParam:haxe.extern.Rest<Any>):Array<S>; dynamic function toJSON():Float; dynamic function valueOf():Float; }; dynamic function has(bit:BitFieldResolvable<S>):Bool; dynamic function missing(bits:BitFieldResolvable<S>, hasParam:haxe.extern.Rest<Any>):Array<S>; dynamic function remove(bits:haxe.extern.Rest<BitFieldResolvable<S>>):BitField<S>; dynamic function serialize(hasParam:haxe.extern.Rest<Any>):{ }; dynamic function toArray(hasParam:haxe.extern.Rest<Any>):Array<S>; dynamic function toJSON():Float; dynamic function valueOf():Float; }; dynamic function has(bit:BitFieldResolvable<S>):Bool; dynamic function missing(bits:BitFieldResolvable<S>, hasParam:haxe.extern.Rest<Any>):Array<S>; dynamic function remove(bits:haxe.extern.Rest<BitFieldResolvable<S>>):BitField<S>; dynamic function serialize(hasParam:haxe.extern.Rest<Any>):{ }; dynamic function toArray(hasParam:haxe.extern.Rest<Any>):Array<S>; dynamic function toJSON():Float; dynamic function valueOf():Float; }; dynamic function has(bit:BitFieldResolvable<S>):Bool; dynamic function missing(bits:BitFieldResolvable<S>, hasParam:haxe.extern.Rest<Any>):Array<S>; dynamic function remove(bits:haxe.extern.Rest<BitFieldResolvable<S>>):BitField<S>; dynamic function serialize(hasParam:haxe.extern.Rest<Any>):{ }; dynamic function toArray(hasParam:haxe.extern.Rest<Any>):Array<S>; dynamic function toJSON():Float; dynamic function valueOf():Float; }; dynamic function has(bit:BitFieldResolvable<S>):Bool; dynamic function missing(bits:BitFieldResolvable<S>, hasParam:haxe.extern.Rest<Any>):Array<S>; dynamic function remove(bits:haxe.extern.Rest<BitFieldResolvable<S>>):BitField<S>; dynamic function serialize(hasParam:haxe.extern.Rest<Any>):{ }; dynamic function toArray(hasParam:haxe.extern.Rest<Any>):Array<S>; dynamic function toJSON():Float; dynamic function valueOf():Float; }; dynamic function has(bit:BitFieldResolvable<S>):Bool; dynamic function missing(bits:BitFieldResolvable<S>, hasParam:haxe.extern.Rest<Any>):Array<S>; dynamic function remove(bits:haxe.extern.Rest<BitFieldResolvable<S>>):BitField<S>; dynamic function serialize(hasParam:haxe.extern.Rest<Any>):{ }; dynamic function toArray(hasParam:haxe.extern.Rest<Any>):Array<S>; dynamic function toJSON():Float; dynamic function valueOf():Float; }; dynamic function has(bit:BitFieldResolvable<S>):Bool; dynamic function missing(bits:BitFieldResolvable<S>, hasParam:haxe.extern.Rest<Any>):Array<S>; dynamic function remove(bits:haxe.extern.Rest<BitFieldResolvable<S>>):BitField<S>; dynamic function serialize(hasParam:haxe.extern.Rest<Any>):{ }; dynamic function toArray(hasParam:haxe.extern.Rest<Any>):Array<S>; dynamic function toJSON():Float; dynamic function valueOf():Float; }; dynamic function has(bit:BitFieldResolvable<S>):Bool; dynamic function missing(bits:BitFieldResolvable<S>, hasParam:haxe.extern.Rest<Any>):Array<S>; dynamic function remove(bits:haxe.extern.Rest<BitFieldResolvable<S>>):BitField<S>; dynamic function serialize(hasParam:haxe.extern.Rest<Any>):{ }; dynamic function toArray(hasParam:haxe.extern.Rest<Any>):Array<S>; dynamic function toJSON():Float; dynamic function valueOf():Float; }; dynamic function has(bit:BitFieldResolvable<S>):Bool; dynamic function missing(bits:BitFieldResolvable<S>, hasParam:haxe.extern.Rest<Any>):Array<S>; dynamic function remove(bits:haxe.extern.Rest<BitFieldResolvable<S>>):BitField<S>; dynamic function serialize(hasParam:haxe.extern.Rest<Any>):{ }; dynamic function toArray(hasParam:haxe.extern.Rest<Any>):Array<S>; dynamic function toJSON():Float; dynamic function valueOf():Float; }; dynamic function has(bit:BitFieldResolvable<S>):Bool; dynamic function missing(bits:BitFieldResolvable<S>, hasParam:haxe.extern.Rest<Any>):Array<S>; dynamic function remove(bits:haxe.extern.Rest<BitFieldResolvable<S>>):BitField<S>; dynamic function serialize(hasParam:haxe.extern.Rest<Any>):{ }; dynamic function toArray(hasParam:haxe.extern.Rest<Any>):Array<S>; dynamic function toJSON():Float; dynamic function valueOf():Float; }; dynamic function has(bit:BitFieldResolvable<S>):Bool; dynamic function missing(bits:BitFieldResolvable<S>, hasParam:haxe.extern.Rest<Any>):Array<S>; dynamic function remove(bits:haxe.extern.Rest<BitFieldResolvable<S>>):BitField<S>; dynamic function serialize(hasParam:haxe.extern.Rest<Any>):{ }; dynamic function toArray(hasParam:haxe.extern.Rest<Any>):Array<S>; dynamic function toJSON():Float; dynamic function valueOf():Float; }; dynamic function has(bit:BitFieldResolvable<S>):Bool; dynamic function missing(bits:BitFieldResolvable<S>, hasParam:haxe.extern.Rest<Any>):Array<S>; dynamic function remove(bits:haxe.extern.Rest<BitFieldResolvable<S>>):BitField<S>; dynamic function serialize(hasParam:haxe.extern.Rest<Any>):{ }; dynamic function toArray(hasParam:haxe.extern.Rest<Any>):Array<S>; dynamic function toJSON():Float; dynamic function valueOf():Float; }; dynamic function has(bit:BitFieldResolvable<S>):Bool; dynamic function missing(bits:BitFieldResolvable<S>, hasParam:haxe.extern.Rest<Any>):Array<S>; dynamic function remove(bits:haxe.extern.Rest<BitFieldResolvable<S>>):BitField<S>; dynamic function serialize(hasParam:haxe.extern.Rest<Any>):{ }; dynamic function toArray(hasParam:haxe.extern.Rest<Any>):Array<S>; dynamic function toJSON():Float; dynamic function valueOf():Float; }; dynamic function has(bit:BitFieldResolvable<S>):Bool; dynamic function missing(bits:BitFieldResolvable<S>, hasParam:haxe.extern.Rest<Any>):Array<S>; dynamic function remove(bits:haxe.extern.Rest<BitFieldResolvable<S>>):BitField<S>; dynamic function serialize(hasParam:haxe.extern.Rest<Any>):{ }; dynamic function toArray(hasParam:haxe.extern.Rest<Any>):Array<S>; dynamic function toJSON():Float; dynamic function valueOf():Float; }, S>);
	public var bitfield : Float;
	public function add(bits:haxe.extern.Rest<BitFieldResolvable<S>>):BitField<S>;
	public function any(bit:BitFieldResolvable<S>):Bool;
	public function equals(bit:BitFieldResolvable<S>):Bool;
	public function freeze():{
		var bitfield : Float;
		dynamic function add(bits:haxe.extern.Rest<BitFieldResolvable<S>>):BitField<S>;
		dynamic function any(bit:BitFieldResolvable<S>):Bool;
		dynamic function equals(bit:BitFieldResolvable<S>):Bool;
		dynamic function freeze():{
			var bitfield : Float;
			dynamic function add(bits:haxe.extern.Rest<BitFieldResolvable<S>>):BitField<S>;
			dynamic function any(bit:BitFieldResolvable<S>):Bool;
			dynamic function equals(bit:BitFieldResolvable<S>):Bool;
			dynamic function freeze():{
				var bitfield : Float;
				dynamic function add(bits:haxe.extern.Rest<BitFieldResolvable<S>>):BitField<S>;
				dynamic function any(bit:BitFieldResolvable<S>):Bool;
				dynamic function equals(bit:BitFieldResolvable<S>):Bool;
				dynamic function freeze():{
					var bitfield : Float;
					dynamic function add(bits:haxe.extern.Rest<BitFieldResolvable<S>>):BitField<S>;
					dynamic function any(bit:BitFieldResolvable<S>):Bool;
					dynamic function equals(bit:BitFieldResolvable<S>):Bool;
					dynamic function freeze():{
						var bitfield : Float;
						dynamic function add(bits:haxe.extern.Rest<BitFieldResolvable<S>>):BitField<S>;
						dynamic function any(bit:BitFieldResolvable<S>):Bool;
						dynamic function equals(bit:BitFieldResolvable<S>):Bool;
						dynamic function freeze():{
							var bitfield : Float;
							dynamic function add(bits:haxe.extern.Rest<BitFieldResolvable<S>>):BitField<S>;
							dynamic function any(bit:BitFieldResolvable<S>):Bool;
							dynamic function equals(bit:BitFieldResolvable<S>):Bool;
							dynamic function freeze():{
								var bitfield : Float;
								dynamic function add(bits:haxe.extern.Rest<BitFieldResolvable<S>>):BitField<S>;
								dynamic function any(bit:BitFieldResolvable<S>):Bool;
								dynamic function equals(bit:BitFieldResolvable<S>):Bool;
								dynamic function freeze():{
									var bitfield : Float;
									dynamic function add(bits:haxe.extern.Rest<BitFieldResolvable<S>>):BitField<S>;
									dynamic function any(bit:BitFieldResolvable<S>):Bool;
									dynamic function equals(bit:BitFieldResolvable<S>):Bool;
									dynamic function freeze():{
										var bitfield : Float;
										dynamic function add(bits:haxe.extern.Rest<BitFieldResolvable<S>>):BitField<S>;
										dynamic function any(bit:BitFieldResolvable<S>):Bool;
										dynamic function equals(bit:BitFieldResolvable<S>):Bool;
										dynamic function freeze():{
											var bitfield : Float;
											dynamic function add(bits:haxe.extern.Rest<BitFieldResolvable<S>>):BitField<S>;
											dynamic function any(bit:BitFieldResolvable<S>):Bool;
											dynamic function equals(bit:BitFieldResolvable<S>):Bool;
											dynamic function freeze():{
												var bitfield : Float;
												dynamic function add(bits:haxe.extern.Rest<BitFieldResolvable<S>>):BitField<S>;
												dynamic function any(bit:BitFieldResolvable<S>):Bool;
												dynamic function equals(bit:BitFieldResolvable<S>):Bool;
												dynamic function freeze():{
													var bitfield : Float;
													dynamic function add(bits:haxe.extern.Rest<BitFieldResolvable<S>>):BitField<S>;
													dynamic function any(bit:BitFieldResolvable<S>):Bool;
													dynamic function equals(bit:BitFieldResolvable<S>):Bool;
													dynamic function freeze():{
														var bitfield : Float;
														dynamic function add(bits:haxe.extern.Rest<BitFieldResolvable<S>>):BitField<S>;
														dynamic function any(bit:BitFieldResolvable<S>):Bool;
														dynamic function equals(bit:BitFieldResolvable<S>):Bool;
														dynamic function freeze():{
															var bitfield : Float;
															dynamic function add(bits:haxe.extern.Rest<BitFieldResolvable<S>>):BitField<S>;
															dynamic function any(bit:BitFieldResolvable<S>):Bool;
															dynamic function equals(bit:BitFieldResolvable<S>):Bool;
															dynamic function freeze():{
																var bitfield : Float;
																dynamic function add(bits:haxe.extern.Rest<BitFieldResolvable<S>>):BitField<S>;
																dynamic function any(bit:BitFieldResolvable<S>):Bool;
																dynamic function equals(bit:BitFieldResolvable<S>):Bool;
																dynamic function freeze():{
																	var bitfield : Float;
																	dynamic function add(bits:haxe.extern.Rest<BitFieldResolvable<S>>):BitField<S>;
																	dynamic function any(bit:BitFieldResolvable<S>):Bool;
																	dynamic function equals(bit:BitFieldResolvable<S>):Bool;
																	dynamic function freeze():{
																		var bitfield : Float;
																		dynamic function add(bits:haxe.extern.Rest<BitFieldResolvable<S>>):BitField<S>;
																		dynamic function any(bit:BitFieldResolvable<S>):Bool;
																		dynamic function equals(bit:BitFieldResolvable<S>):Bool;
																		dynamic function freeze():{
																			var bitfield : Float;
																			dynamic function add(bits:haxe.extern.Rest<BitFieldResolvable<S>>):BitField<S>;
																			dynamic function any(bit:BitFieldResolvable<S>):Bool;
																			dynamic function equals(bit:BitFieldResolvable<S>):Bool;
																			dynamic function freeze():{
																				var bitfield : Float;
																				dynamic function add(bits:haxe.extern.Rest<BitFieldResolvable<S>>):BitField<S>;
																				dynamic function any(bit:BitFieldResolvable<S>):Bool;
																				dynamic function equals(bit:BitFieldResolvable<S>):Bool;
																				dynamic function freeze():{
																					var bitfield : Float;
																					dynamic function add(bits:haxe.extern.Rest<BitFieldResolvable<S>>):BitField<S>;
																					dynamic function any(bit:BitFieldResolvable<S>):Bool;
																					dynamic function equals(bit:BitFieldResolvable<S>):Bool;
																					dynamic function freeze():{
																						var bitfield : Float;
																						dynamic function add(bits:haxe.extern.Rest<BitFieldResolvable<S>>):BitField<S>;
																						dynamic function any(bit:BitFieldResolvable<S>):Bool;
																						dynamic function equals(bit:BitFieldResolvable<S>):Bool;
																						dynamic function freeze():{
																							var bitfield : Float;
																							dynamic function add(bits:haxe.extern.Rest<BitFieldResolvable<S>>):BitField<S>;
																							dynamic function any(bit:BitFieldResolvable<S>):Bool;
																							dynamic function equals(bit:BitFieldResolvable<S>):Bool;
																							dynamic function freeze():{
																								var bitfield : Float;
																								dynamic function add(bits:haxe.extern.Rest<BitFieldResolvable<Dynamic>>):BitField<S>;
																								dynamic function any(bit:BitFieldResolvable<S>):Bool;
																								dynamic function equals(bit:BitFieldResolvable<S>):Bool;
																								dynamic function freeze():{
																									var bitfield : Float;
																									dynamic function add(bits:haxe.extern.Rest<Any>):BitField<S>;
																									dynamic function any(bit:BitFieldResolvable<Dynamic>):Bool;
																									dynamic function equals(bit:BitFieldResolvable<Dynamic>):Bool;
																									dynamic function freeze():{
																										var bitfield : Dynamic;
																										dynamic function add(bits:haxe.extern.Rest<Any>):Dynamic;
																										dynamic function any(bit:Dynamic):Dynamic;
																										dynamic function equals(bit:Dynamic):Dynamic;
																										dynamic function freeze():Dynamic;
																										dynamic function has(bit:Dynamic):Dynamic;
																										dynamic function missing(bits:Dynamic, hasParam:haxe.extern.Rest<Any>):Dynamic;
																										dynamic function remove(bits:haxe.extern.Rest<Any>):Dynamic;
																										dynamic function serialize(hasParam:haxe.extern.Rest<Any>):Dynamic;
																										dynamic function toArray(hasParam:haxe.extern.Rest<Any>):Dynamic;
																										dynamic function toJSON():Dynamic;
																										dynamic function valueOf():Dynamic;
																									};
																									dynamic function has(bit:BitFieldResolvable<Dynamic>):Bool;
																									dynamic function missing(bits:BitFieldResolvable<Dynamic>, hasParam:haxe.extern.Rest<Any>):Dynamic<Dynamic>;
																									dynamic function remove(bits:haxe.extern.Rest<Any>):BitField<S>;
																									dynamic function serialize(hasParam:haxe.extern.Rest<Any>):{ };
																									dynamic function toArray(hasParam:haxe.extern.Rest<Any>):Dynamic<Dynamic>;
																									dynamic function toJSON():Float;
																									dynamic function valueOf():Float;
																								};
																								dynamic function has(bit:BitFieldResolvable<S>):Bool;
																								dynamic function missing(bits:BitFieldResolvable<S>, hasParam:haxe.extern.Rest<Any>):Array<S>;
																								dynamic function remove(bits:haxe.extern.Rest<BitFieldResolvable<Dynamic>>):BitField<S>;
																								dynamic function serialize(hasParam:haxe.extern.Rest<Any>):{ };
																								dynamic function toArray(hasParam:haxe.extern.Rest<Any>):Array<S>;
																								dynamic function toJSON():Float;
																								dynamic function valueOf():Float;
																							};
																							dynamic function has(bit:BitFieldResolvable<S>):Bool;
																							dynamic function missing(bits:BitFieldResolvable<S>, hasParam:haxe.extern.Rest<Any>):Array<S>;
																							dynamic function remove(bits:haxe.extern.Rest<BitFieldResolvable<S>>):BitField<S>;
																							dynamic function serialize(hasParam:haxe.extern.Rest<Any>):{ };
																							dynamic function toArray(hasParam:haxe.extern.Rest<Any>):Array<S>;
																							dynamic function toJSON():Float;
																							dynamic function valueOf():Float;
																						};
																						dynamic function has(bit:BitFieldResolvable<S>):Bool;
																						dynamic function missing(bits:BitFieldResolvable<S>, hasParam:haxe.extern.Rest<Any>):Array<S>;
																						dynamic function remove(bits:haxe.extern.Rest<BitFieldResolvable<S>>):BitField<S>;
																						dynamic function serialize(hasParam:haxe.extern.Rest<Any>):{ };
																						dynamic function toArray(hasParam:haxe.extern.Rest<Any>):Array<S>;
																						dynamic function toJSON():Float;
																						dynamic function valueOf():Float;
																					};
																					dynamic function has(bit:BitFieldResolvable<S>):Bool;
																					dynamic function missing(bits:BitFieldResolvable<S>, hasParam:haxe.extern.Rest<Any>):Array<S>;
																					dynamic function remove(bits:haxe.extern.Rest<BitFieldResolvable<S>>):BitField<S>;
																					dynamic function serialize(hasParam:haxe.extern.Rest<Any>):{ };
																					dynamic function toArray(hasParam:haxe.extern.Rest<Any>):Array<S>;
																					dynamic function toJSON():Float;
																					dynamic function valueOf():Float;
																				};
																				dynamic function has(bit:BitFieldResolvable<S>):Bool;
																				dynamic function missing(bits:BitFieldResolvable<S>, hasParam:haxe.extern.Rest<Any>):Array<S>;
																				dynamic function remove(bits:haxe.extern.Rest<BitFieldResolvable<S>>):BitField<S>;
																				dynamic function serialize(hasParam:haxe.extern.Rest<Any>):{ };
																				dynamic function toArray(hasParam:haxe.extern.Rest<Any>):Array<S>;
																				dynamic function toJSON():Float;
																				dynamic function valueOf():Float;
																			};
																			dynamic function has(bit:BitFieldResolvable<S>):Bool;
																			dynamic function missing(bits:BitFieldResolvable<S>, hasParam:haxe.extern.Rest<Any>):Array<S>;
																			dynamic function remove(bits:haxe.extern.Rest<BitFieldResolvable<S>>):BitField<S>;
																			dynamic function serialize(hasParam:haxe.extern.Rest<Any>):{ };
																			dynamic function toArray(hasParam:haxe.extern.Rest<Any>):Array<S>;
																			dynamic function toJSON():Float;
																			dynamic function valueOf():Float;
																		};
																		dynamic function has(bit:BitFieldResolvable<S>):Bool;
																		dynamic function missing(bits:BitFieldResolvable<S>, hasParam:haxe.extern.Rest<Any>):Array<S>;
																		dynamic function remove(bits:haxe.extern.Rest<BitFieldResolvable<S>>):BitField<S>;
																		dynamic function serialize(hasParam:haxe.extern.Rest<Any>):{ };
																		dynamic function toArray(hasParam:haxe.extern.Rest<Any>):Array<S>;
																		dynamic function toJSON():Float;
																		dynamic function valueOf():Float;
																	};
																	dynamic function has(bit:BitFieldResolvable<S>):Bool;
																	dynamic function missing(bits:BitFieldResolvable<S>, hasParam:haxe.extern.Rest<Any>):Array<S>;
																	dynamic function remove(bits:haxe.extern.Rest<BitFieldResolvable<S>>):BitField<S>;
																	dynamic function serialize(hasParam:haxe.extern.Rest<Any>):{ };
																	dynamic function toArray(hasParam:haxe.extern.Rest<Any>):Array<S>;
																	dynamic function toJSON():Float;
																	dynamic function valueOf():Float;
																};
																dynamic function has(bit:BitFieldResolvable<S>):Bool;
																dynamic function missing(bits:BitFieldResolvable<S>, hasParam:haxe.extern.Rest<Any>):Array<S>;
																dynamic function remove(bits:haxe.extern.Rest<BitFieldResolvable<S>>):BitField<S>;
																dynamic function serialize(hasParam:haxe.extern.Rest<Any>):{ };
																dynamic function toArray(hasParam:haxe.extern.Rest<Any>):Array<S>;
																dynamic function toJSON():Float;
																dynamic function valueOf():Float;
															};
															dynamic function has(bit:BitFieldResolvable<S>):Bool;
															dynamic function missing(bits:BitFieldResolvable<S>, hasParam:haxe.extern.Rest<Any>):Array<S>;
															dynamic function remove(bits:haxe.extern.Rest<BitFieldResolvable<S>>):BitField<S>;
															dynamic function serialize(hasParam:haxe.extern.Rest<Any>):{ };
															dynamic function toArray(hasParam:haxe.extern.Rest<Any>):Array<S>;
															dynamic function toJSON():Float;
															dynamic function valueOf():Float;
														};
														dynamic function has(bit:BitFieldResolvable<S>):Bool;
														dynamic function missing(bits:BitFieldResolvable<S>, hasParam:haxe.extern.Rest<Any>):Array<S>;
														dynamic function remove(bits:haxe.extern.Rest<BitFieldResolvable<S>>):BitField<S>;
														dynamic function serialize(hasParam:haxe.extern.Rest<Any>):{ };
														dynamic function toArray(hasParam:haxe.extern.Rest<Any>):Array<S>;
														dynamic function toJSON():Float;
														dynamic function valueOf():Float;
													};
													dynamic function has(bit:BitFieldResolvable<S>):Bool;
													dynamic function missing(bits:BitFieldResolvable<S>, hasParam:haxe.extern.Rest<Any>):Array<S>;
													dynamic function remove(bits:haxe.extern.Rest<BitFieldResolvable<S>>):BitField<S>;
													dynamic function serialize(hasParam:haxe.extern.Rest<Any>):{ };
													dynamic function toArray(hasParam:haxe.extern.Rest<Any>):Array<S>;
													dynamic function toJSON():Float;
													dynamic function valueOf():Float;
												};
												dynamic function has(bit:BitFieldResolvable<S>):Bool;
												dynamic function missing(bits:BitFieldResolvable<S>, hasParam:haxe.extern.Rest<Any>):Array<S>;
												dynamic function remove(bits:haxe.extern.Rest<BitFieldResolvable<S>>):BitField<S>;
												dynamic function serialize(hasParam:haxe.extern.Rest<Any>):{ };
												dynamic function toArray(hasParam:haxe.extern.Rest<Any>):Array<S>;
												dynamic function toJSON():Float;
												dynamic function valueOf():Float;
											};
											dynamic function has(bit:BitFieldResolvable<S>):Bool;
											dynamic function missing(bits:BitFieldResolvable<S>, hasParam:haxe.extern.Rest<Any>):Array<S>;
											dynamic function remove(bits:haxe.extern.Rest<BitFieldResolvable<S>>):BitField<S>;
											dynamic function serialize(hasParam:haxe.extern.Rest<Any>):{ };
											dynamic function toArray(hasParam:haxe.extern.Rest<Any>):Array<S>;
											dynamic function toJSON():Float;
											dynamic function valueOf():Float;
										};
										dynamic function has(bit:BitFieldResolvable<S>):Bool;
										dynamic function missing(bits:BitFieldResolvable<S>, hasParam:haxe.extern.Rest<Any>):Array<S>;
										dynamic function remove(bits:haxe.extern.Rest<BitFieldResolvable<S>>):BitField<S>;
										dynamic function serialize(hasParam:haxe.extern.Rest<Any>):{ };
										dynamic function toArray(hasParam:haxe.extern.Rest<Any>):Array<S>;
										dynamic function toJSON():Float;
										dynamic function valueOf():Float;
									};
									dynamic function has(bit:BitFieldResolvable<S>):Bool;
									dynamic function missing(bits:BitFieldResolvable<S>, hasParam:haxe.extern.Rest<Any>):Array<S>;
									dynamic function remove(bits:haxe.extern.Rest<BitFieldResolvable<S>>):BitField<S>;
									dynamic function serialize(hasParam:haxe.extern.Rest<Any>):{ };
									dynamic function toArray(hasParam:haxe.extern.Rest<Any>):Array<S>;
									dynamic function toJSON():Float;
									dynamic function valueOf():Float;
								};
								dynamic function has(bit:BitFieldResolvable<S>):Bool;
								dynamic function missing(bits:BitFieldResolvable<S>, hasParam:haxe.extern.Rest<Any>):Array<S>;
								dynamic function remove(bits:haxe.extern.Rest<BitFieldResolvable<S>>):BitField<S>;
								dynamic function serialize(hasParam:haxe.extern.Rest<Any>):{ };
								dynamic function toArray(hasParam:haxe.extern.Rest<Any>):Array<S>;
								dynamic function toJSON():Float;
								dynamic function valueOf():Float;
							};
							dynamic function has(bit:BitFieldResolvable<S>):Bool;
							dynamic function missing(bits:BitFieldResolvable<S>, hasParam:haxe.extern.Rest<Any>):Array<S>;
							dynamic function remove(bits:haxe.extern.Rest<BitFieldResolvable<S>>):BitField<S>;
							dynamic function serialize(hasParam:haxe.extern.Rest<Any>):{ };
							dynamic function toArray(hasParam:haxe.extern.Rest<Any>):Array<S>;
							dynamic function toJSON():Float;
							dynamic function valueOf():Float;
						};
						dynamic function has(bit:BitFieldResolvable<S>):Bool;
						dynamic function missing(bits:BitFieldResolvable<S>, hasParam:haxe.extern.Rest<Any>):Array<S>;
						dynamic function remove(bits:haxe.extern.Rest<BitFieldResolvable<S>>):BitField<S>;
						dynamic function serialize(hasParam:haxe.extern.Rest<Any>):{ };
						dynamic function toArray(hasParam:haxe.extern.Rest<Any>):Array<S>;
						dynamic function toJSON():Float;
						dynamic function valueOf():Float;
					};
					dynamic function has(bit:BitFieldResolvable<S>):Bool;
					dynamic function missing(bits:BitFieldResolvable<S>, hasParam:haxe.extern.Rest<Any>):Array<S>;
					dynamic function remove(bits:haxe.extern.Rest<BitFieldResolvable<S>>):BitField<S>;
					dynamic function serialize(hasParam:haxe.extern.Rest<Any>):{ };
					dynamic function toArray(hasParam:haxe.extern.Rest<Any>):Array<S>;
					dynamic function toJSON():Float;
					dynamic function valueOf():Float;
				};
				dynamic function has(bit:BitFieldResolvable<S>):Bool;
				dynamic function missing(bits:BitFieldResolvable<S>, hasParam:haxe.extern.Rest<Any>):Array<S>;
				dynamic function remove(bits:haxe.extern.Rest<BitFieldResolvable<S>>):BitField<S>;
				dynamic function serialize(hasParam:haxe.extern.Rest<Any>):{ };
				dynamic function toArray(hasParam:haxe.extern.Rest<Any>):Array<S>;
				dynamic function toJSON():Float;
				dynamic function valueOf():Float;
			};
			dynamic function has(bit:BitFieldResolvable<S>):Bool;
			dynamic function missing(bits:BitFieldResolvable<S>, hasParam:haxe.extern.Rest<Any>):Array<S>;
			dynamic function remove(bits:haxe.extern.Rest<BitFieldResolvable<S>>):BitField<S>;
			dynamic function serialize(hasParam:haxe.extern.Rest<Any>):{ };
			dynamic function toArray(hasParam:haxe.extern.Rest<Any>):Array<S>;
			dynamic function toJSON():Float;
			dynamic function valueOf():Float;
		};
		dynamic function has(bit:BitFieldResolvable<S>):Bool;
		dynamic function missing(bits:BitFieldResolvable<S>, hasParam:haxe.extern.Rest<Any>):Array<S>;
		dynamic function remove(bits:haxe.extern.Rest<BitFieldResolvable<S>>):BitField<S>;
		dynamic function serialize(hasParam:haxe.extern.Rest<Any>):{ };
		dynamic function toArray(hasParam:haxe.extern.Rest<Any>):Array<S>;
		dynamic function toJSON():Float;
		dynamic function valueOf():Float;
	};
	public function has(bit:BitFieldResolvable<S>):Bool;
	public function missing(bits:BitFieldResolvable<S>, hasParam:haxe.extern.Rest<Any>):Array<S>;
	public function remove(bits:haxe.extern.Rest<BitFieldResolvable<S>>):BitField<S>;
	public function serialize(hasParam:haxe.extern.Rest<Any>):{ };
	public function toArray(hasParam:haxe.extern.Rest<Any>):Array<S>;
	public function toJSON():Float;
	public function valueOf():Float;
	static var prototype : BitField<Dynamic>;
	public static var FLAGS : Dynamic;
	public static function resolve(?bit:Dynamic):Float;
}