package discord_js;

typedef BitFieldResolvable<T> = ts.AnyOf4<Float, RecursiveReadonlyArray<ts.AnyOf3<Float, {
	var bitfield : Float;
	dynamic function add(bits:haxe.extern.Rest<BitFieldResolvable<T>>):BitField<T>;
	dynamic function any(bit:BitFieldResolvable<T>):Bool;
	dynamic function equals(bit:BitFieldResolvable<T>):Bool;
	dynamic function freeze():{
		var bitfield : Float;
		dynamic function add(bits:haxe.extern.Rest<BitFieldResolvable<T>>):BitField<T>;
		dynamic function any(bit:BitFieldResolvable<T>):Bool;
		dynamic function equals(bit:BitFieldResolvable<T>):Bool;
		dynamic function freeze():{
			var bitfield : Float;
			dynamic function add(bits:haxe.extern.Rest<BitFieldResolvable<T>>):BitField<T>;
			dynamic function any(bit:BitFieldResolvable<T>):Bool;
			dynamic function equals(bit:BitFieldResolvable<T>):Bool;
			dynamic function freeze():{
				var bitfield : Float;
				dynamic function add(bits:haxe.extern.Rest<BitFieldResolvable<T>>):BitField<T>;
				dynamic function any(bit:BitFieldResolvable<T>):Bool;
				dynamic function equals(bit:BitFieldResolvable<T>):Bool;
				dynamic function freeze():{
					var bitfield : Float;
					dynamic function add(bits:haxe.extern.Rest<BitFieldResolvable<T>>):BitField<T>;
					dynamic function any(bit:BitFieldResolvable<T>):Bool;
					dynamic function equals(bit:BitFieldResolvable<T>):Bool;
					dynamic function freeze():{
						var bitfield : Float;
						dynamic function add(bits:haxe.extern.Rest<BitFieldResolvable<T>>):BitField<T>;
						dynamic function any(bit:BitFieldResolvable<T>):Bool;
						dynamic function equals(bit:BitFieldResolvable<T>):Bool;
						dynamic function freeze():{
							var bitfield : Float;
							dynamic function add(bits:haxe.extern.Rest<BitFieldResolvable<T>>):BitField<T>;
							dynamic function any(bit:BitFieldResolvable<T>):Bool;
							dynamic function equals(bit:BitFieldResolvable<T>):Bool;
							dynamic function freeze():{
								var bitfield : Float;
								dynamic function add(bits:haxe.extern.Rest<BitFieldResolvable<T>>):BitField<T>;
								dynamic function any(bit:BitFieldResolvable<T>):Bool;
								dynamic function equals(bit:BitFieldResolvable<T>):Bool;
								dynamic function freeze():{
									var bitfield : Float;
									dynamic function add(bits:haxe.extern.Rest<BitFieldResolvable<T>>):BitField<T>;
									dynamic function any(bit:BitFieldResolvable<T>):Bool;
									dynamic function equals(bit:BitFieldResolvable<T>):Bool;
									dynamic function freeze():{
										var bitfield : Float;
										dynamic function add(bits:haxe.extern.Rest<BitFieldResolvable<T>>):BitField<T>;
										dynamic function any(bit:BitFieldResolvable<T>):Bool;
										dynamic function equals(bit:BitFieldResolvable<T>):Bool;
										dynamic function freeze():{
											var bitfield : Float;
											dynamic function add(bits:haxe.extern.Rest<BitFieldResolvable<T>>):BitField<T>;
											dynamic function any(bit:BitFieldResolvable<T>):Bool;
											dynamic function equals(bit:BitFieldResolvable<T>):Bool;
											dynamic function freeze():{
												var bitfield : Float;
												dynamic function add(bits:haxe.extern.Rest<BitFieldResolvable<T>>):BitField<T>;
												dynamic function any(bit:BitFieldResolvable<T>):Bool;
												dynamic function equals(bit:BitFieldResolvable<T>):Bool;
												dynamic function freeze():{
													var bitfield : Float;
													dynamic function add(bits:haxe.extern.Rest<BitFieldResolvable<T>>):BitField<T>;
													dynamic function any(bit:BitFieldResolvable<T>):Bool;
													dynamic function equals(bit:BitFieldResolvable<T>):Bool;
													dynamic function freeze():{
														var bitfield : Float;
														dynamic function add(bits:haxe.extern.Rest<BitFieldResolvable<T>>):BitField<T>;
														dynamic function any(bit:BitFieldResolvable<T>):Bool;
														dynamic function equals(bit:BitFieldResolvable<T>):Bool;
														dynamic function freeze():{
															var bitfield : Float;
															dynamic function add(bits:haxe.extern.Rest<BitFieldResolvable<T>>):BitField<T>;
															dynamic function any(bit:BitFieldResolvable<T>):Bool;
															dynamic function equals(bit:BitFieldResolvable<T>):Bool;
															dynamic function freeze():{
																var bitfield : Float;
																dynamic function add(bits:haxe.extern.Rest<BitFieldResolvable<T>>):BitField<T>;
																dynamic function any(bit:BitFieldResolvable<T>):Bool;
																dynamic function equals(bit:BitFieldResolvable<T>):Bool;
																dynamic function freeze():{
																	var bitfield : Float;
																	dynamic function add(bits:haxe.extern.Rest<BitFieldResolvable<T>>):BitField<T>;
																	dynamic function any(bit:BitFieldResolvable<T>):Bool;
																	dynamic function equals(bit:BitFieldResolvable<T>):Bool;
																	dynamic function freeze():{
																		var bitfield : Float;
																		dynamic function add(bits:haxe.extern.Rest<BitFieldResolvable<T>>):BitField<T>;
																		dynamic function any(bit:BitFieldResolvable<T>):Bool;
																		dynamic function equals(bit:BitFieldResolvable<T>):Bool;
																		dynamic function freeze():{
																			var bitfield : Float;
																			dynamic function add(bits:haxe.extern.Rest<BitFieldResolvable<T>>):BitField<T>;
																			dynamic function any(bit:BitFieldResolvable<T>):Bool;
																			dynamic function equals(bit:BitFieldResolvable<T>):Bool;
																			dynamic function freeze():{
																				var bitfield : Float;
																				dynamic function add(bits:haxe.extern.Rest<BitFieldResolvable<Dynamic>>):BitField<T>;
																				dynamic function any(bit:BitFieldResolvable<T>):Bool;
																				dynamic function equals(bit:BitFieldResolvable<T>):Bool;
																				dynamic function freeze():{
																					var bitfield : Float;
																					dynamic function add(bits:haxe.extern.Rest<Any>):Dynamic<Dynamic>;
																					dynamic function any(bit:BitFieldResolvable<Dynamic>):Bool;
																					dynamic function equals(bit:BitFieldResolvable<Dynamic>):Bool;
																					dynamic function freeze():{
																						var bitfield : Dynamic;
																						dynamic function add(bits:haxe.extern.Rest<Any>):Dynamic;
																						dynamic function any(bit:Dynamic):Dynamic;
																						dynamic function equals(bit:Dynamic):Dynamic;
																						dynamic function freeze():Dynamic;
																						dynamic function has(bit:Dynamic):Dynamic;
																						dynamic function missing(bits:Dynamic, hasParam:haxe.extern.Rest<Any>):Dynamic;
																						dynamic function remove(bits:haxe.extern.Rest<Any>):Dynamic;
																						dynamic function serialize(hasParam:haxe.extern.Rest<Any>):Dynamic;
																						dynamic function toArray(hasParam:haxe.extern.Rest<Any>):Dynamic;
																						dynamic function toJSON():Dynamic;
																						dynamic function valueOf():Dynamic;
																					};
																					dynamic function has(bit:BitFieldResolvable<Dynamic>):Bool;
																					dynamic function missing(bits:BitFieldResolvable<Dynamic>, hasParam:haxe.extern.Rest<Any>):Dynamic<Dynamic>;
																					dynamic function remove(bits:haxe.extern.Rest<Any>):Dynamic<Dynamic>;
																					dynamic function serialize(hasParam:haxe.extern.Rest<Any>):{ };
																					dynamic function toArray(hasParam:haxe.extern.Rest<Any>):Dynamic<Dynamic>;
																					dynamic function toJSON():Float;
																					dynamic function valueOf():Float;
																				};
																				dynamic function has(bit:BitFieldResolvable<T>):Bool;
																				dynamic function missing(bits:BitFieldResolvable<T>, hasParam:haxe.extern.Rest<Any>):Array<T>;
																				dynamic function remove(bits:haxe.extern.Rest<BitFieldResolvable<Dynamic>>):BitField<T>;
																				dynamic function serialize(hasParam:haxe.extern.Rest<Any>):{ };
																				dynamic function toArray(hasParam:haxe.extern.Rest<Any>):Array<T>;
																				dynamic function toJSON():Float;
																				dynamic function valueOf():Float;
																			};
																			dynamic function has(bit:BitFieldResolvable<T>):Bool;
																			dynamic function missing(bits:BitFieldResolvable<T>, hasParam:haxe.extern.Rest<Any>):Array<T>;
																			dynamic function remove(bits:haxe.extern.Rest<BitFieldResolvable<T>>):BitField<T>;
																			dynamic function serialize(hasParam:haxe.extern.Rest<Any>):{ };
																			dynamic function toArray(hasParam:haxe.extern.Rest<Any>):Array<T>;
																			dynamic function toJSON():Float;
																			dynamic function valueOf():Float;
																		};
																		dynamic function has(bit:BitFieldResolvable<T>):Bool;
																		dynamic function missing(bits:BitFieldResolvable<T>, hasParam:haxe.extern.Rest<Any>):Array<T>;
																		dynamic function remove(bits:haxe.extern.Rest<BitFieldResolvable<T>>):BitField<T>;
																		dynamic function serialize(hasParam:haxe.extern.Rest<Any>):{ };
																		dynamic function toArray(hasParam:haxe.extern.Rest<Any>):Array<T>;
																		dynamic function toJSON():Float;
																		dynamic function valueOf():Float;
																	};
																	dynamic function has(bit:BitFieldResolvable<T>):Bool;
																	dynamic function missing(bits:BitFieldResolvable<T>, hasParam:haxe.extern.Rest<Any>):Array<T>;
																	dynamic function remove(bits:haxe.extern.Rest<BitFieldResolvable<T>>):BitField<T>;
																	dynamic function serialize(hasParam:haxe.extern.Rest<Any>):{ };
																	dynamic function toArray(hasParam:haxe.extern.Rest<Any>):Array<T>;
																	dynamic function toJSON():Float;
																	dynamic function valueOf():Float;
																};
																dynamic function has(bit:BitFieldResolvable<T>):Bool;
																dynamic function missing(bits:BitFieldResolvable<T>, hasParam:haxe.extern.Rest<Any>):Array<T>;
																dynamic function remove(bits:haxe.extern.Rest<BitFieldResolvable<T>>):BitField<T>;
																dynamic function serialize(hasParam:haxe.extern.Rest<Any>):{ };
																dynamic function toArray(hasParam:haxe.extern.Rest<Any>):Array<T>;
																dynamic function toJSON():Float;
																dynamic function valueOf():Float;
															};
															dynamic function has(bit:BitFieldResolvable<T>):Bool;
															dynamic function missing(bits:BitFieldResolvable<T>, hasParam:haxe.extern.Rest<Any>):Array<T>;
															dynamic function remove(bits:haxe.extern.Rest<BitFieldResolvable<T>>):BitField<T>;
															dynamic function serialize(hasParam:haxe.extern.Rest<Any>):{ };
															dynamic function toArray(hasParam:haxe.extern.Rest<Any>):Array<T>;
															dynamic function toJSON():Float;
															dynamic function valueOf():Float;
														};
														dynamic function has(bit:BitFieldResolvable<T>):Bool;
														dynamic function missing(bits:BitFieldResolvable<T>, hasParam:haxe.extern.Rest<Any>):Array<T>;
														dynamic function remove(bits:haxe.extern.Rest<BitFieldResolvable<T>>):BitField<T>;
														dynamic function serialize(hasParam:haxe.extern.Rest<Any>):{ };
														dynamic function toArray(hasParam:haxe.extern.Rest<Any>):Array<T>;
														dynamic function toJSON():Float;
														dynamic function valueOf():Float;
													};
													dynamic function has(bit:BitFieldResolvable<T>):Bool;
													dynamic function missing(bits:BitFieldResolvable<T>, hasParam:haxe.extern.Rest<Any>):Array<T>;
													dynamic function remove(bits:haxe.extern.Rest<BitFieldResolvable<T>>):BitField<T>;
													dynamic function serialize(hasParam:haxe.extern.Rest<Any>):{ };
													dynamic function toArray(hasParam:haxe.extern.Rest<Any>):Array<T>;
													dynamic function toJSON():Float;
													dynamic function valueOf():Float;
												};
												dynamic function has(bit:BitFieldResolvable<T>):Bool;
												dynamic function missing(bits:BitFieldResolvable<T>, hasParam:haxe.extern.Rest<Any>):Array<T>;
												dynamic function remove(bits:haxe.extern.Rest<BitFieldResolvable<T>>):BitField<T>;
												dynamic function serialize(hasParam:haxe.extern.Rest<Any>):{ };
												dynamic function toArray(hasParam:haxe.extern.Rest<Any>):Array<T>;
												dynamic function toJSON():Float;
												dynamic function valueOf():Float;
											};
											dynamic function has(bit:BitFieldResolvable<T>):Bool;
											dynamic function missing(bits:BitFieldResolvable<T>, hasParam:haxe.extern.Rest<Any>):Array<T>;
											dynamic function remove(bits:haxe.extern.Rest<BitFieldResolvable<T>>):BitField<T>;
											dynamic function serialize(hasParam:haxe.extern.Rest<Any>):{ };
											dynamic function toArray(hasParam:haxe.extern.Rest<Any>):Array<T>;
											dynamic function toJSON():Float;
											dynamic function valueOf():Float;
										};
										dynamic function has(bit:BitFieldResolvable<T>):Bool;
										dynamic function missing(bits:BitFieldResolvable<T>, hasParam:haxe.extern.Rest<Any>):Array<T>;
										dynamic function remove(bits:haxe.extern.Rest<BitFieldResolvable<T>>):BitField<T>;
										dynamic function serialize(hasParam:haxe.extern.Rest<Any>):{ };
										dynamic function toArray(hasParam:haxe.extern.Rest<Any>):Array<T>;
										dynamic function toJSON():Float;
										dynamic function valueOf():Float;
									};
									dynamic function has(bit:BitFieldResolvable<T>):Bool;
									dynamic function missing(bits:BitFieldResolvable<T>, hasParam:haxe.extern.Rest<Any>):Array<T>;
									dynamic function remove(bits:haxe.extern.Rest<BitFieldResolvable<T>>):BitField<T>;
									dynamic function serialize(hasParam:haxe.extern.Rest<Any>):{ };
									dynamic function toArray(hasParam:haxe.extern.Rest<Any>):Array<T>;
									dynamic function toJSON():Float;
									dynamic function valueOf():Float;
								};
								dynamic function has(bit:BitFieldResolvable<T>):Bool;
								dynamic function missing(bits:BitFieldResolvable<T>, hasParam:haxe.extern.Rest<Any>):Array<T>;
								dynamic function remove(bits:haxe.extern.Rest<BitFieldResolvable<T>>):BitField<T>;
								dynamic function serialize(hasParam:haxe.extern.Rest<Any>):{ };
								dynamic function toArray(hasParam:haxe.extern.Rest<Any>):Array<T>;
								dynamic function toJSON():Float;
								dynamic function valueOf():Float;
							};
							dynamic function has(bit:BitFieldResolvable<T>):Bool;
							dynamic function missing(bits:BitFieldResolvable<T>, hasParam:haxe.extern.Rest<Any>):Array<T>;
							dynamic function remove(bits:haxe.extern.Rest<BitFieldResolvable<T>>):BitField<T>;
							dynamic function serialize(hasParam:haxe.extern.Rest<Any>):{ };
							dynamic function toArray(hasParam:haxe.extern.Rest<Any>):Array<T>;
							dynamic function toJSON():Float;
							dynamic function valueOf():Float;
						};
						dynamic function has(bit:BitFieldResolvable<T>):Bool;
						dynamic function missing(bits:BitFieldResolvable<T>, hasParam:haxe.extern.Rest<Any>):Array<T>;
						dynamic function remove(bits:haxe.extern.Rest<BitFieldResolvable<T>>):BitField<T>;
						dynamic function serialize(hasParam:haxe.extern.Rest<Any>):{ };
						dynamic function toArray(hasParam:haxe.extern.Rest<Any>):Array<T>;
						dynamic function toJSON():Float;
						dynamic function valueOf():Float;
					};
					dynamic function has(bit:BitFieldResolvable<T>):Bool;
					dynamic function missing(bits:BitFieldResolvable<T>, hasParam:haxe.extern.Rest<Any>):Array<T>;
					dynamic function remove(bits:haxe.extern.Rest<BitFieldResolvable<T>>):BitField<T>;
					dynamic function serialize(hasParam:haxe.extern.Rest<Any>):{ };
					dynamic function toArray(hasParam:haxe.extern.Rest<Any>):Array<T>;
					dynamic function toJSON():Float;
					dynamic function valueOf():Float;
				};
				dynamic function has(bit:BitFieldResolvable<T>):Bool;
				dynamic function missing(bits:BitFieldResolvable<T>, hasParam:haxe.extern.Rest<Any>):Array<T>;
				dynamic function remove(bits:haxe.extern.Rest<BitFieldResolvable<T>>):BitField<T>;
				dynamic function serialize(hasParam:haxe.extern.Rest<Any>):{ };
				dynamic function toArray(hasParam:haxe.extern.Rest<Any>):Array<T>;
				dynamic function toJSON():Float;
				dynamic function valueOf():Float;
			};
			dynamic function has(bit:BitFieldResolvable<T>):Bool;
			dynamic function missing(bits:BitFieldResolvable<T>, hasParam:haxe.extern.Rest<Any>):Array<T>;
			dynamic function remove(bits:haxe.extern.Rest<BitFieldResolvable<T>>):BitField<T>;
			dynamic function serialize(hasParam:haxe.extern.Rest<Any>):{ };
			dynamic function toArray(hasParam:haxe.extern.Rest<Any>):Array<T>;
			dynamic function toJSON():Float;
			dynamic function valueOf():Float;
		};
		dynamic function has(bit:BitFieldResolvable<T>):Bool;
		dynamic function missing(bits:BitFieldResolvable<T>, hasParam:haxe.extern.Rest<Any>):Array<T>;
		dynamic function remove(bits:haxe.extern.Rest<BitFieldResolvable<T>>):BitField<T>;
		dynamic function serialize(hasParam:haxe.extern.Rest<Any>):{ };
		dynamic function toArray(hasParam:haxe.extern.Rest<Any>):Array<T>;
		dynamic function toJSON():Float;
		dynamic function valueOf():Float;
	};
	dynamic function has(bit:BitFieldResolvable<T>):Bool;
	dynamic function missing(bits:BitFieldResolvable<T>, hasParam:haxe.extern.Rest<Any>):Array<T>;
	dynamic function remove(bits:haxe.extern.Rest<BitFieldResolvable<T>>):BitField<T>;
	dynamic function serialize(hasParam:haxe.extern.Rest<Any>):{ };
	dynamic function toArray(hasParam:haxe.extern.Rest<Any>):Array<T>;
	dynamic function toJSON():Float;
	dynamic function valueOf():Float;
}, T>>, {
	var bitfield : Float;
	dynamic function add(bits:haxe.extern.Rest<BitFieldResolvable<T>>):BitField<T>;
	dynamic function any(bit:BitFieldResolvable<T>):Bool;
	dynamic function equals(bit:BitFieldResolvable<T>):Bool;
	dynamic function freeze():{
		var bitfield : Float;
		dynamic function add(bits:haxe.extern.Rest<BitFieldResolvable<T>>):BitField<T>;
		dynamic function any(bit:BitFieldResolvable<T>):Bool;
		dynamic function equals(bit:BitFieldResolvable<T>):Bool;
		dynamic function freeze():{
			var bitfield : Float;
			dynamic function add(bits:haxe.extern.Rest<BitFieldResolvable<T>>):BitField<T>;
			dynamic function any(bit:BitFieldResolvable<T>):Bool;
			dynamic function equals(bit:BitFieldResolvable<T>):Bool;
			dynamic function freeze():{
				var bitfield : Float;
				dynamic function add(bits:haxe.extern.Rest<BitFieldResolvable<T>>):BitField<T>;
				dynamic function any(bit:BitFieldResolvable<T>):Bool;
				dynamic function equals(bit:BitFieldResolvable<T>):Bool;
				dynamic function freeze():{
					var bitfield : Float;
					dynamic function add(bits:haxe.extern.Rest<BitFieldResolvable<T>>):BitField<T>;
					dynamic function any(bit:BitFieldResolvable<T>):Bool;
					dynamic function equals(bit:BitFieldResolvable<T>):Bool;
					dynamic function freeze():{
						var bitfield : Float;
						dynamic function add(bits:haxe.extern.Rest<BitFieldResolvable<T>>):BitField<T>;
						dynamic function any(bit:BitFieldResolvable<T>):Bool;
						dynamic function equals(bit:BitFieldResolvable<T>):Bool;
						dynamic function freeze():{
							var bitfield : Float;
							dynamic function add(bits:haxe.extern.Rest<BitFieldResolvable<T>>):BitField<T>;
							dynamic function any(bit:BitFieldResolvable<T>):Bool;
							dynamic function equals(bit:BitFieldResolvable<T>):Bool;
							dynamic function freeze():{
								var bitfield : Float;
								dynamic function add(bits:haxe.extern.Rest<BitFieldResolvable<T>>):BitField<T>;
								dynamic function any(bit:BitFieldResolvable<T>):Bool;
								dynamic function equals(bit:BitFieldResolvable<T>):Bool;
								dynamic function freeze():{
									var bitfield : Float;
									dynamic function add(bits:haxe.extern.Rest<BitFieldResolvable<T>>):BitField<T>;
									dynamic function any(bit:BitFieldResolvable<T>):Bool;
									dynamic function equals(bit:BitFieldResolvable<T>):Bool;
									dynamic function freeze():{
										var bitfield : Float;
										dynamic function add(bits:haxe.extern.Rest<BitFieldResolvable<T>>):BitField<T>;
										dynamic function any(bit:BitFieldResolvable<T>):Bool;
										dynamic function equals(bit:BitFieldResolvable<T>):Bool;
										dynamic function freeze():{
											var bitfield : Float;
											dynamic function add(bits:haxe.extern.Rest<BitFieldResolvable<T>>):BitField<T>;
											dynamic function any(bit:BitFieldResolvable<T>):Bool;
											dynamic function equals(bit:BitFieldResolvable<T>):Bool;
											dynamic function freeze():{
												var bitfield : Float;
												dynamic function add(bits:haxe.extern.Rest<BitFieldResolvable<T>>):BitField<T>;
												dynamic function any(bit:BitFieldResolvable<T>):Bool;
												dynamic function equals(bit:BitFieldResolvable<T>):Bool;
												dynamic function freeze():{
													var bitfield : Float;
													dynamic function add(bits:haxe.extern.Rest<BitFieldResolvable<T>>):BitField<T>;
													dynamic function any(bit:BitFieldResolvable<T>):Bool;
													dynamic function equals(bit:BitFieldResolvable<T>):Bool;
													dynamic function freeze():{
														var bitfield : Float;
														dynamic function add(bits:haxe.extern.Rest<BitFieldResolvable<T>>):BitField<T>;
														dynamic function any(bit:BitFieldResolvable<T>):Bool;
														dynamic function equals(bit:BitFieldResolvable<T>):Bool;
														dynamic function freeze():{
															var bitfield : Float;
															dynamic function add(bits:haxe.extern.Rest<BitFieldResolvable<T>>):BitField<T>;
															dynamic function any(bit:BitFieldResolvable<T>):Bool;
															dynamic function equals(bit:BitFieldResolvable<T>):Bool;
															dynamic function freeze():{
																var bitfield : Float;
																dynamic function add(bits:haxe.extern.Rest<BitFieldResolvable<T>>):BitField<T>;
																dynamic function any(bit:BitFieldResolvable<T>):Bool;
																dynamic function equals(bit:BitFieldResolvable<T>):Bool;
																dynamic function freeze():{
																	var bitfield : Float;
																	dynamic function add(bits:haxe.extern.Rest<BitFieldResolvable<T>>):BitField<T>;
																	dynamic function any(bit:BitFieldResolvable<T>):Bool;
																	dynamic function equals(bit:BitFieldResolvable<T>):Bool;
																	dynamic function freeze():{
																		var bitfield : Float;
																		dynamic function add(bits:haxe.extern.Rest<BitFieldResolvable<T>>):BitField<T>;
																		dynamic function any(bit:BitFieldResolvable<T>):Bool;
																		dynamic function equals(bit:BitFieldResolvable<T>):Bool;
																		dynamic function freeze():{
																			var bitfield : Float;
																			dynamic function add(bits:haxe.extern.Rest<BitFieldResolvable<T>>):BitField<T>;
																			dynamic function any(bit:BitFieldResolvable<T>):Bool;
																			dynamic function equals(bit:BitFieldResolvable<T>):Bool;
																			dynamic function freeze():{
																				var bitfield : Float;
																				dynamic function add(bits:haxe.extern.Rest<BitFieldResolvable<T>>):BitField<T>;
																				dynamic function any(bit:BitFieldResolvable<T>):Bool;
																				dynamic function equals(bit:BitFieldResolvable<T>):Bool;
																				dynamic function freeze():{
																					var bitfield : Float;
																					dynamic function add(bits:haxe.extern.Rest<BitFieldResolvable<T>>):BitField<T>;
																					dynamic function any(bit:BitFieldResolvable<T>):Bool;
																					dynamic function equals(bit:BitFieldResolvable<T>):Bool;
																					dynamic function freeze():{
																						var bitfield : Float;
																						dynamic function add(bits:haxe.extern.Rest<BitFieldResolvable<Dynamic>>):BitField<T>;
																						dynamic function any(bit:BitFieldResolvable<T>):Bool;
																						dynamic function equals(bit:BitFieldResolvable<T>):Bool;
																						dynamic function freeze():{
																							var bitfield : Float;
																							dynamic function add(bits:haxe.extern.Rest<Any>):Dynamic<Dynamic>;
																							dynamic function any(bit:BitFieldResolvable<Dynamic>):Bool;
																							dynamic function equals(bit:BitFieldResolvable<Dynamic>):Bool;
																							dynamic function freeze():{
																								var bitfield : Dynamic;
																								dynamic function add(bits:haxe.extern.Rest<Any>):Dynamic;
																								dynamic function any(bit:Dynamic):Dynamic;
																								dynamic function equals(bit:Dynamic):Dynamic;
																								dynamic function freeze():Dynamic;
																								dynamic function has(bit:Dynamic):Dynamic;
																								dynamic function missing(bits:Dynamic, hasParam:haxe.extern.Rest<Any>):Dynamic;
																								dynamic function remove(bits:haxe.extern.Rest<Any>):Dynamic;
																								dynamic function serialize(hasParam:haxe.extern.Rest<Any>):Dynamic;
																								dynamic function toArray(hasParam:haxe.extern.Rest<Any>):Dynamic;
																								dynamic function toJSON():Dynamic;
																								dynamic function valueOf():Dynamic;
																							};
																							dynamic function has(bit:BitFieldResolvable<Dynamic>):Bool;
																							dynamic function missing(bits:BitFieldResolvable<Dynamic>, hasParam:haxe.extern.Rest<Any>):Dynamic<Dynamic>;
																							dynamic function remove(bits:haxe.extern.Rest<Any>):Dynamic<Dynamic>;
																							dynamic function serialize(hasParam:haxe.extern.Rest<Any>):{ };
																							dynamic function toArray(hasParam:haxe.extern.Rest<Any>):Dynamic<Dynamic>;
																							dynamic function toJSON():Float;
																							dynamic function valueOf():Float;
																						};
																						dynamic function has(bit:BitFieldResolvable<T>):Bool;
																						dynamic function missing(bits:BitFieldResolvable<T>, hasParam:haxe.extern.Rest<Any>):Array<T>;
																						dynamic function remove(bits:haxe.extern.Rest<BitFieldResolvable<Dynamic>>):BitField<T>;
																						dynamic function serialize(hasParam:haxe.extern.Rest<Any>):{ };
																						dynamic function toArray(hasParam:haxe.extern.Rest<Any>):Array<T>;
																						dynamic function toJSON():Float;
																						dynamic function valueOf():Float;
																					};
																					dynamic function has(bit:BitFieldResolvable<T>):Bool;
																					dynamic function missing(bits:BitFieldResolvable<T>, hasParam:haxe.extern.Rest<Any>):Array<T>;
																					dynamic function remove(bits:haxe.extern.Rest<BitFieldResolvable<T>>):BitField<T>;
																					dynamic function serialize(hasParam:haxe.extern.Rest<Any>):{ };
																					dynamic function toArray(hasParam:haxe.extern.Rest<Any>):Array<T>;
																					dynamic function toJSON():Float;
																					dynamic function valueOf():Float;
																				};
																				dynamic function has(bit:BitFieldResolvable<T>):Bool;
																				dynamic function missing(bits:BitFieldResolvable<T>, hasParam:haxe.extern.Rest<Any>):Array<T>;
																				dynamic function remove(bits:haxe.extern.Rest<BitFieldResolvable<T>>):BitField<T>;
																				dynamic function serialize(hasParam:haxe.extern.Rest<Any>):{ };
																				dynamic function toArray(hasParam:haxe.extern.Rest<Any>):Array<T>;
																				dynamic function toJSON():Float;
																				dynamic function valueOf():Float;
																			};
																			dynamic function has(bit:BitFieldResolvable<T>):Bool;
																			dynamic function missing(bits:BitFieldResolvable<T>, hasParam:haxe.extern.Rest<Any>):Array<T>;
																			dynamic function remove(bits:haxe.extern.Rest<BitFieldResolvable<T>>):BitField<T>;
																			dynamic function serialize(hasParam:haxe.extern.Rest<Any>):{ };
																			dynamic function toArray(hasParam:haxe.extern.Rest<Any>):Array<T>;
																			dynamic function toJSON():Float;
																			dynamic function valueOf():Float;
																		};
																		dynamic function has(bit:BitFieldResolvable<T>):Bool;
																		dynamic function missing(bits:BitFieldResolvable<T>, hasParam:haxe.extern.Rest<Any>):Array<T>;
																		dynamic function remove(bits:haxe.extern.Rest<BitFieldResolvable<T>>):BitField<T>;
																		dynamic function serialize(hasParam:haxe.extern.Rest<Any>):{ };
																		dynamic function toArray(hasParam:haxe.extern.Rest<Any>):Array<T>;
																		dynamic function toJSON():Float;
																		dynamic function valueOf():Float;
																	};
																	dynamic function has(bit:BitFieldResolvable<T>):Bool;
																	dynamic function missing(bits:BitFieldResolvable<T>, hasParam:haxe.extern.Rest<Any>):Array<T>;
																	dynamic function remove(bits:haxe.extern.Rest<BitFieldResolvable<T>>):BitField<T>;
																	dynamic function serialize(hasParam:haxe.extern.Rest<Any>):{ };
																	dynamic function toArray(hasParam:haxe.extern.Rest<Any>):Array<T>;
																	dynamic function toJSON():Float;
																	dynamic function valueOf():Float;
																};
																dynamic function has(bit:BitFieldResolvable<T>):Bool;
																dynamic function missing(bits:BitFieldResolvable<T>, hasParam:haxe.extern.Rest<Any>):Array<T>;
																dynamic function remove(bits:haxe.extern.Rest<BitFieldResolvable<T>>):BitField<T>;
																dynamic function serialize(hasParam:haxe.extern.Rest<Any>):{ };
																dynamic function toArray(hasParam:haxe.extern.Rest<Any>):Array<T>;
																dynamic function toJSON():Float;
																dynamic function valueOf():Float;
															};
															dynamic function has(bit:BitFieldResolvable<T>):Bool;
															dynamic function missing(bits:BitFieldResolvable<T>, hasParam:haxe.extern.Rest<Any>):Array<T>;
															dynamic function remove(bits:haxe.extern.Rest<BitFieldResolvable<T>>):BitField<T>;
															dynamic function serialize(hasParam:haxe.extern.Rest<Any>):{ };
															dynamic function toArray(hasParam:haxe.extern.Rest<Any>):Array<T>;
															dynamic function toJSON():Float;
															dynamic function valueOf():Float;
														};
														dynamic function has(bit:BitFieldResolvable<T>):Bool;
														dynamic function missing(bits:BitFieldResolvable<T>, hasParam:haxe.extern.Rest<Any>):Array<T>;
														dynamic function remove(bits:haxe.extern.Rest<BitFieldResolvable<T>>):BitField<T>;
														dynamic function serialize(hasParam:haxe.extern.Rest<Any>):{ };
														dynamic function toArray(hasParam:haxe.extern.Rest<Any>):Array<T>;
														dynamic function toJSON():Float;
														dynamic function valueOf():Float;
													};
													dynamic function has(bit:BitFieldResolvable<T>):Bool;
													dynamic function missing(bits:BitFieldResolvable<T>, hasParam:haxe.extern.Rest<Any>):Array<T>;
													dynamic function remove(bits:haxe.extern.Rest<BitFieldResolvable<T>>):BitField<T>;
													dynamic function serialize(hasParam:haxe.extern.Rest<Any>):{ };
													dynamic function toArray(hasParam:haxe.extern.Rest<Any>):Array<T>;
													dynamic function toJSON():Float;
													dynamic function valueOf():Float;
												};
												dynamic function has(bit:BitFieldResolvable<T>):Bool;
												dynamic function missing(bits:BitFieldResolvable<T>, hasParam:haxe.extern.Rest<Any>):Array<T>;
												dynamic function remove(bits:haxe.extern.Rest<BitFieldResolvable<T>>):BitField<T>;
												dynamic function serialize(hasParam:haxe.extern.Rest<Any>):{ };
												dynamic function toArray(hasParam:haxe.extern.Rest<Any>):Array<T>;
												dynamic function toJSON():Float;
												dynamic function valueOf():Float;
											};
											dynamic function has(bit:BitFieldResolvable<T>):Bool;
											dynamic function missing(bits:BitFieldResolvable<T>, hasParam:haxe.extern.Rest<Any>):Array<T>;
											dynamic function remove(bits:haxe.extern.Rest<BitFieldResolvable<T>>):BitField<T>;
											dynamic function serialize(hasParam:haxe.extern.Rest<Any>):{ };
											dynamic function toArray(hasParam:haxe.extern.Rest<Any>):Array<T>;
											dynamic function toJSON():Float;
											dynamic function valueOf():Float;
										};
										dynamic function has(bit:BitFieldResolvable<T>):Bool;
										dynamic function missing(bits:BitFieldResolvable<T>, hasParam:haxe.extern.Rest<Any>):Array<T>;
										dynamic function remove(bits:haxe.extern.Rest<BitFieldResolvable<T>>):BitField<T>;
										dynamic function serialize(hasParam:haxe.extern.Rest<Any>):{ };
										dynamic function toArray(hasParam:haxe.extern.Rest<Any>):Array<T>;
										dynamic function toJSON():Float;
										dynamic function valueOf():Float;
									};
									dynamic function has(bit:BitFieldResolvable<T>):Bool;
									dynamic function missing(bits:BitFieldResolvable<T>, hasParam:haxe.extern.Rest<Any>):Array<T>;
									dynamic function remove(bits:haxe.extern.Rest<BitFieldResolvable<T>>):BitField<T>;
									dynamic function serialize(hasParam:haxe.extern.Rest<Any>):{ };
									dynamic function toArray(hasParam:haxe.extern.Rest<Any>):Array<T>;
									dynamic function toJSON():Float;
									dynamic function valueOf():Float;
								};
								dynamic function has(bit:BitFieldResolvable<T>):Bool;
								dynamic function missing(bits:BitFieldResolvable<T>, hasParam:haxe.extern.Rest<Any>):Array<T>;
								dynamic function remove(bits:haxe.extern.Rest<BitFieldResolvable<T>>):BitField<T>;
								dynamic function serialize(hasParam:haxe.extern.Rest<Any>):{ };
								dynamic function toArray(hasParam:haxe.extern.Rest<Any>):Array<T>;
								dynamic function toJSON():Float;
								dynamic function valueOf():Float;
							};
							dynamic function has(bit:BitFieldResolvable<T>):Bool;
							dynamic function missing(bits:BitFieldResolvable<T>, hasParam:haxe.extern.Rest<Any>):Array<T>;
							dynamic function remove(bits:haxe.extern.Rest<BitFieldResolvable<T>>):BitField<T>;
							dynamic function serialize(hasParam:haxe.extern.Rest<Any>):{ };
							dynamic function toArray(hasParam:haxe.extern.Rest<Any>):Array<T>;
							dynamic function toJSON():Float;
							dynamic function valueOf():Float;
						};
						dynamic function has(bit:BitFieldResolvable<T>):Bool;
						dynamic function missing(bits:BitFieldResolvable<T>, hasParam:haxe.extern.Rest<Any>):Array<T>;
						dynamic function remove(bits:haxe.extern.Rest<BitFieldResolvable<T>>):BitField<T>;
						dynamic function serialize(hasParam:haxe.extern.Rest<Any>):{ };
						dynamic function toArray(hasParam:haxe.extern.Rest<Any>):Array<T>;
						dynamic function toJSON():Float;
						dynamic function valueOf():Float;
					};
					dynamic function has(bit:BitFieldResolvable<T>):Bool;
					dynamic function missing(bits:BitFieldResolvable<T>, hasParam:haxe.extern.Rest<Any>):Array<T>;
					dynamic function remove(bits:haxe.extern.Rest<BitFieldResolvable<T>>):BitField<T>;
					dynamic function serialize(hasParam:haxe.extern.Rest<Any>):{ };
					dynamic function toArray(hasParam:haxe.extern.Rest<Any>):Array<T>;
					dynamic function toJSON():Float;
					dynamic function valueOf():Float;
				};
				dynamic function has(bit:BitFieldResolvable<T>):Bool;
				dynamic function missing(bits:BitFieldResolvable<T>, hasParam:haxe.extern.Rest<Any>):Array<T>;
				dynamic function remove(bits:haxe.extern.Rest<BitFieldResolvable<T>>):BitField<T>;
				dynamic function serialize(hasParam:haxe.extern.Rest<Any>):{ };
				dynamic function toArray(hasParam:haxe.extern.Rest<Any>):Array<T>;
				dynamic function toJSON():Float;
				dynamic function valueOf():Float;
			};
			dynamic function has(bit:BitFieldResolvable<T>):Bool;
			dynamic function missing(bits:BitFieldResolvable<T>, hasParam:haxe.extern.Rest<Any>):Array<T>;
			dynamic function remove(bits:haxe.extern.Rest<BitFieldResolvable<T>>):BitField<T>;
			dynamic function serialize(hasParam:haxe.extern.Rest<Any>):{ };
			dynamic function toArray(hasParam:haxe.extern.Rest<Any>):Array<T>;
			dynamic function toJSON():Float;
			dynamic function valueOf():Float;
		};
		dynamic function has(bit:BitFieldResolvable<T>):Bool;
		dynamic function missing(bits:BitFieldResolvable<T>, hasParam:haxe.extern.Rest<Any>):Array<T>;
		dynamic function remove(bits:haxe.extern.Rest<BitFieldResolvable<T>>):BitField<T>;
		dynamic function serialize(hasParam:haxe.extern.Rest<Any>):{ };
		dynamic function toArray(hasParam:haxe.extern.Rest<Any>):Array<T>;
		dynamic function toJSON():Float;
		dynamic function valueOf():Float;
	};
	dynamic function has(bit:BitFieldResolvable<T>):Bool;
	dynamic function missing(bits:BitFieldResolvable<T>, hasParam:haxe.extern.Rest<Any>):Array<T>;
	dynamic function remove(bits:haxe.extern.Rest<BitFieldResolvable<T>>):BitField<T>;
	dynamic function serialize(hasParam:haxe.extern.Rest<Any>):{ };
	dynamic function toArray(hasParam:haxe.extern.Rest<Any>):Array<T>;
	dynamic function toJSON():Float;
	dynamic function valueOf():Float;
}, T>;