package discord_js;

typedef PartialUser = {
	var bot : Bool;
	var flags : Null<{
		var bitfield : Float;
		dynamic function add(bits:haxe.extern.Rest<BitFieldResolvable<UserFlagsString>>):BitField<UserFlagsString>;
		dynamic function any(bit:BitFieldResolvable<UserFlagsString>):Bool;
		dynamic function equals(bit:BitFieldResolvable<UserFlagsString>):Bool;
		dynamic function freeze():{
			var bitfield : Float;
			dynamic function add(bits:haxe.extern.Rest<BitFieldResolvable<UserFlagsString>>):BitField<UserFlagsString>;
			dynamic function any(bit:BitFieldResolvable<UserFlagsString>):Bool;
			dynamic function equals(bit:BitFieldResolvable<UserFlagsString>):Bool;
			dynamic function freeze():{
				var bitfield : Float;
				dynamic function add(bits:haxe.extern.Rest<BitFieldResolvable<UserFlagsString>>):BitField<UserFlagsString>;
				dynamic function any(bit:BitFieldResolvable<UserFlagsString>):Bool;
				dynamic function equals(bit:BitFieldResolvable<UserFlagsString>):Bool;
				dynamic function freeze():{
					var bitfield : Float;
					dynamic function add(bits:haxe.extern.Rest<BitFieldResolvable<UserFlagsString>>):BitField<UserFlagsString>;
					dynamic function any(bit:BitFieldResolvable<UserFlagsString>):Bool;
					dynamic function equals(bit:BitFieldResolvable<UserFlagsString>):Bool;
					dynamic function freeze():{
						var bitfield : Float;
						dynamic function add(bits:haxe.extern.Rest<BitFieldResolvable<UserFlagsString>>):BitField<UserFlagsString>;
						dynamic function any(bit:BitFieldResolvable<UserFlagsString>):Bool;
						dynamic function equals(bit:BitFieldResolvable<UserFlagsString>):Bool;
						dynamic function freeze():{
							var bitfield : Float;
							dynamic function add(bits:haxe.extern.Rest<BitFieldResolvable<UserFlagsString>>):BitField<UserFlagsString>;
							dynamic function any(bit:BitFieldResolvable<UserFlagsString>):Bool;
							dynamic function equals(bit:BitFieldResolvable<UserFlagsString>):Bool;
							dynamic function freeze():{
								var bitfield : Float;
								dynamic function add(bits:haxe.extern.Rest<BitFieldResolvable<UserFlagsString>>):BitField<UserFlagsString>;
								dynamic function any(bit:BitFieldResolvable<UserFlagsString>):Bool;
								dynamic function equals(bit:BitFieldResolvable<UserFlagsString>):Bool;
								dynamic function freeze():{
									var bitfield : Float;
									dynamic function add(bits:haxe.extern.Rest<BitFieldResolvable<UserFlagsString>>):BitField<UserFlagsString>;
									dynamic function any(bit:BitFieldResolvable<UserFlagsString>):Bool;
									dynamic function equals(bit:BitFieldResolvable<UserFlagsString>):Bool;
									dynamic function freeze():{
										var bitfield : Float;
										dynamic function add(bits:haxe.extern.Rest<BitFieldResolvable<UserFlagsString>>):BitField<UserFlagsString>;
										dynamic function any(bit:BitFieldResolvable<UserFlagsString>):Bool;
										dynamic function equals(bit:BitFieldResolvable<UserFlagsString>):Bool;
										dynamic function freeze():{
											var bitfield : Float;
											dynamic function add(bits:haxe.extern.Rest<BitFieldResolvable<UserFlagsString>>):BitField<UserFlagsString>;
											dynamic function any(bit:BitFieldResolvable<UserFlagsString>):Bool;
											dynamic function equals(bit:BitFieldResolvable<UserFlagsString>):Bool;
											dynamic function freeze():{
												var bitfield : Float;
												dynamic function add(bits:haxe.extern.Rest<BitFieldResolvable<UserFlagsString>>):BitField<UserFlagsString>;
												dynamic function any(bit:BitFieldResolvable<UserFlagsString>):Bool;
												dynamic function equals(bit:BitFieldResolvable<UserFlagsString>):Bool;
												dynamic function freeze():{
													var bitfield : Float;
													dynamic function add(bits:haxe.extern.Rest<BitFieldResolvable<UserFlagsString>>):BitField<UserFlagsString>;
													dynamic function any(bit:BitFieldResolvable<UserFlagsString>):Bool;
													dynamic function equals(bit:BitFieldResolvable<UserFlagsString>):Bool;
													dynamic function freeze():{
														var bitfield : Float;
														dynamic function add(bits:haxe.extern.Rest<BitFieldResolvable<UserFlagsString>>):BitField<UserFlagsString>;
														dynamic function any(bit:BitFieldResolvable<UserFlagsString>):Bool;
														dynamic function equals(bit:BitFieldResolvable<UserFlagsString>):Bool;
														dynamic function freeze():{
															var bitfield : Float;
															dynamic function add(bits:haxe.extern.Rest<BitFieldResolvable<UserFlagsString>>):BitField<UserFlagsString>;
															dynamic function any(bit:BitFieldResolvable<UserFlagsString>):Bool;
															dynamic function equals(bit:BitFieldResolvable<UserFlagsString>):Bool;
															dynamic function freeze():{
																var bitfield : Float;
																dynamic function add(bits:haxe.extern.Rest<BitFieldResolvable<UserFlagsString>>):BitField<UserFlagsString>;
																dynamic function any(bit:BitFieldResolvable<UserFlagsString>):Bool;
																dynamic function equals(bit:BitFieldResolvable<UserFlagsString>):Bool;
																dynamic function freeze():{
																	var bitfield : Float;
																	dynamic function add(bits:haxe.extern.Rest<BitFieldResolvable<UserFlagsString>>):BitField<UserFlagsString>;
																	dynamic function any(bit:BitFieldResolvable<UserFlagsString>):Bool;
																	dynamic function equals(bit:BitFieldResolvable<UserFlagsString>):Bool;
																	dynamic function freeze():{
																		var bitfield : Float;
																		dynamic function add(bits:haxe.extern.Rest<BitFieldResolvable<UserFlagsString>>):BitField<UserFlagsString>;
																		dynamic function any(bit:BitFieldResolvable<UserFlagsString>):Bool;
																		dynamic function equals(bit:BitFieldResolvable<UserFlagsString>):Bool;
																		dynamic function freeze():{
																			var bitfield : Float;
																			dynamic function add(bits:haxe.extern.Rest<BitFieldResolvable<UserFlagsString>>):BitField<UserFlagsString>;
																			dynamic function any(bit:BitFieldResolvable<UserFlagsString>):Bool;
																			dynamic function equals(bit:BitFieldResolvable<UserFlagsString>):Bool;
																			dynamic function freeze():{
																				var bitfield : Float;
																				dynamic function add(bits:haxe.extern.Rest<BitFieldResolvable<UserFlagsString>>):BitField<UserFlagsString>;
																				dynamic function any(bit:BitFieldResolvable<UserFlagsString>):Bool;
																				dynamic function equals(bit:BitFieldResolvable<UserFlagsString>):Bool;
																				dynamic function freeze():{
																					var bitfield : Float;
																					dynamic function add(bits:haxe.extern.Rest<BitFieldResolvable<UserFlagsString>>):BitField<UserFlagsString>;
																					dynamic function any(bit:BitFieldResolvable<UserFlagsString>):Bool;
																					dynamic function equals(bit:BitFieldResolvable<UserFlagsString>):Bool;
																					dynamic function freeze():{
																						var bitfield : Float;
																						dynamic function add(bits:haxe.extern.Rest<BitFieldResolvable<UserFlagsString>>):BitField<UserFlagsString>;
																						dynamic function any(bit:BitFieldResolvable<UserFlagsString>):Bool;
																						dynamic function equals(bit:BitFieldResolvable<UserFlagsString>):Bool;
																						dynamic function freeze():{
																							var bitfield : Float;
																							dynamic function add(bits:haxe.extern.Rest<BitFieldResolvable<Dynamic>>):BitField<UserFlagsString>;
																							dynamic function any(bit:BitFieldResolvable<UserFlagsString>):Bool;
																							dynamic function equals(bit:BitFieldResolvable<UserFlagsString>):Bool;
																							dynamic function freeze():{
																								var bitfield : Float;
																								dynamic function add(bits:haxe.extern.Rest<Any>):Dynamic<Dynamic>;
																								dynamic function any(bit:BitFieldResolvable<Dynamic>):Bool;
																								dynamic function equals(bit:BitFieldResolvable<Dynamic>):Bool;
																								dynamic function freeze():{
																									var bitfield : Dynamic;
																									dynamic function add(bits:haxe.extern.Rest<Any>):Dynamic;
																									dynamic function any(bit:Dynamic):Dynamic;
																									dynamic function equals(bit:Dynamic):Dynamic;
																									dynamic function freeze():Dynamic;
																									dynamic function has(bit:Dynamic):Dynamic;
																									dynamic function missing(bits:Dynamic, hasParam:haxe.extern.Rest<Any>):Dynamic;
																									dynamic function remove(bits:haxe.extern.Rest<Any>):Dynamic;
																									dynamic function serialize(hasParam:haxe.extern.Rest<Any>):Dynamic;
																									dynamic function toArray(hasParam:haxe.extern.Rest<Any>):Dynamic;
																									dynamic function toJSON():Dynamic;
																									dynamic function valueOf():Dynamic;
																								};
																								dynamic function has(bit:BitFieldResolvable<Dynamic>):Bool;
																								dynamic function missing(bits:BitFieldResolvable<Dynamic>, hasParam:haxe.extern.Rest<Any>):Dynamic<Dynamic>;
																								dynamic function remove(bits:haxe.extern.Rest<Any>):Dynamic<Dynamic>;
																								dynamic function serialize(hasParam:haxe.extern.Rest<Any>):{
																									var DISCORD_EMPLOYEE : Dynamic;
																									var PARTNERED_SERVER_OWNER : Dynamic;
																									var DISCORD_PARTNER : Dynamic;
																									var HYPESQUAD_EVENTS : Dynamic;
																									var BUGHUNTER_LEVEL_1 : Dynamic;
																									var HOUSE_BRAVERY : Dynamic;
																									var HOUSE_BRILLIANCE : Dynamic;
																									var HOUSE_BALANCE : Dynamic;
																									var EARLY_SUPPORTER : Dynamic;
																									var TEAM_USER : Dynamic;
																									var SYSTEM : Dynamic;
																									var BUGHUNTER_LEVEL_2 : Dynamic;
																									var VERIFIED_BOT : Dynamic;
																									var EARLY_VERIFIED_DEVELOPER : Dynamic;
																									var VERIFIED_DEVELOPER : Dynamic;
																								};
																								dynamic function toArray(hasParam:haxe.extern.Rest<Any>):Dynamic<Dynamic>;
																								dynamic function toJSON():Float;
																								dynamic function valueOf():Float;
																							};
																							dynamic function has(bit:BitFieldResolvable<UserFlagsString>):Bool;
																							dynamic function missing(bits:BitFieldResolvable<UserFlagsString>, hasParam:haxe.extern.Rest<Any>):Array<UserFlagsString>;
																							dynamic function remove(bits:haxe.extern.Rest<BitFieldResolvable<Dynamic>>):BitField<UserFlagsString>;
																							dynamic function serialize(hasParam:haxe.extern.Rest<Any>):{
																								var DISCORD_EMPLOYEE : Bool;
																								var PARTNERED_SERVER_OWNER : Bool;
																								var DISCORD_PARTNER : Bool;
																								var HYPESQUAD_EVENTS : Bool;
																								var BUGHUNTER_LEVEL_1 : Bool;
																								var HOUSE_BRAVERY : Bool;
																								var HOUSE_BRILLIANCE : Bool;
																								var HOUSE_BALANCE : Bool;
																								var EARLY_SUPPORTER : Bool;
																								var TEAM_USER : Bool;
																								var SYSTEM : Bool;
																								var BUGHUNTER_LEVEL_2 : Bool;
																								var VERIFIED_BOT : Bool;
																								var EARLY_VERIFIED_DEVELOPER : Bool;
																								var VERIFIED_DEVELOPER : Bool;
																							};
																							dynamic function toArray(hasParam:haxe.extern.Rest<Any>):Array<UserFlagsString>;
																							dynamic function toJSON():Float;
																							dynamic function valueOf():Float;
																						};
																						dynamic function has(bit:BitFieldResolvable<UserFlagsString>):Bool;
																						dynamic function missing(bits:BitFieldResolvable<UserFlagsString>, hasParam:haxe.extern.Rest<Any>):Array<UserFlagsString>;
																						dynamic function remove(bits:haxe.extern.Rest<BitFieldResolvable<UserFlagsString>>):BitField<UserFlagsString>;
																						dynamic function serialize(hasParam:haxe.extern.Rest<Any>):{
																							var DISCORD_EMPLOYEE : Bool;
																							var PARTNERED_SERVER_OWNER : Bool;
																							var DISCORD_PARTNER : Bool;
																							var HYPESQUAD_EVENTS : Bool;
																							var BUGHUNTER_LEVEL_1 : Bool;
																							var HOUSE_BRAVERY : Bool;
																							var HOUSE_BRILLIANCE : Bool;
																							var HOUSE_BALANCE : Bool;
																							var EARLY_SUPPORTER : Bool;
																							var TEAM_USER : Bool;
																							var SYSTEM : Bool;
																							var BUGHUNTER_LEVEL_2 : Bool;
																							var VERIFIED_BOT : Bool;
																							var EARLY_VERIFIED_DEVELOPER : Bool;
																							var VERIFIED_DEVELOPER : Bool;
																						};
																						dynamic function toArray(hasParam:haxe.extern.Rest<Any>):Array<UserFlagsString>;
																						dynamic function toJSON():Float;
																						dynamic function valueOf():Float;
																					};
																					dynamic function has(bit:BitFieldResolvable<UserFlagsString>):Bool;
																					dynamic function missing(bits:BitFieldResolvable<UserFlagsString>, hasParam:haxe.extern.Rest<Any>):Array<UserFlagsString>;
																					dynamic function remove(bits:haxe.extern.Rest<BitFieldResolvable<UserFlagsString>>):BitField<UserFlagsString>;
																					dynamic function serialize(hasParam:haxe.extern.Rest<Any>):{
																						var DISCORD_EMPLOYEE : Bool;
																						var PARTNERED_SERVER_OWNER : Bool;
																						var DISCORD_PARTNER : Bool;
																						var HYPESQUAD_EVENTS : Bool;
																						var BUGHUNTER_LEVEL_1 : Bool;
																						var HOUSE_BRAVERY : Bool;
																						var HOUSE_BRILLIANCE : Bool;
																						var HOUSE_BALANCE : Bool;
																						var EARLY_SUPPORTER : Bool;
																						var TEAM_USER : Bool;
																						var SYSTEM : Bool;
																						var BUGHUNTER_LEVEL_2 : Bool;
																						var VERIFIED_BOT : Bool;
																						var EARLY_VERIFIED_DEVELOPER : Bool;
																						var VERIFIED_DEVELOPER : Bool;
																					};
																					dynamic function toArray(hasParam:haxe.extern.Rest<Any>):Array<UserFlagsString>;
																					dynamic function toJSON():Float;
																					dynamic function valueOf():Float;
																				};
																				dynamic function has(bit:BitFieldResolvable<UserFlagsString>):Bool;
																				dynamic function missing(bits:BitFieldResolvable<UserFlagsString>, hasParam:haxe.extern.Rest<Any>):Array<UserFlagsString>;
																				dynamic function remove(bits:haxe.extern.Rest<BitFieldResolvable<UserFlagsString>>):BitField<UserFlagsString>;
																				dynamic function serialize(hasParam:haxe.extern.Rest<Any>):{
																					var DISCORD_EMPLOYEE : Bool;
																					var PARTNERED_SERVER_OWNER : Bool;
																					var DISCORD_PARTNER : Bool;
																					var HYPESQUAD_EVENTS : Bool;
																					var BUGHUNTER_LEVEL_1 : Bool;
																					var HOUSE_BRAVERY : Bool;
																					var HOUSE_BRILLIANCE : Bool;
																					var HOUSE_BALANCE : Bool;
																					var EARLY_SUPPORTER : Bool;
																					var TEAM_USER : Bool;
																					var SYSTEM : Bool;
																					var BUGHUNTER_LEVEL_2 : Bool;
																					var VERIFIED_BOT : Bool;
																					var EARLY_VERIFIED_DEVELOPER : Bool;
																					var VERIFIED_DEVELOPER : Bool;
																				};
																				dynamic function toArray(hasParam:haxe.extern.Rest<Any>):Array<UserFlagsString>;
																				dynamic function toJSON():Float;
																				dynamic function valueOf():Float;
																			};
																			dynamic function has(bit:BitFieldResolvable<UserFlagsString>):Bool;
																			dynamic function missing(bits:BitFieldResolvable<UserFlagsString>, hasParam:haxe.extern.Rest<Any>):Array<UserFlagsString>;
																			dynamic function remove(bits:haxe.extern.Rest<BitFieldResolvable<UserFlagsString>>):BitField<UserFlagsString>;
																			dynamic function serialize(hasParam:haxe.extern.Rest<Any>):{
																				var DISCORD_EMPLOYEE : Bool;
																				var PARTNERED_SERVER_OWNER : Bool;
																				var DISCORD_PARTNER : Bool;
																				var HYPESQUAD_EVENTS : Bool;
																				var BUGHUNTER_LEVEL_1 : Bool;
																				var HOUSE_BRAVERY : Bool;
																				var HOUSE_BRILLIANCE : Bool;
																				var HOUSE_BALANCE : Bool;
																				var EARLY_SUPPORTER : Bool;
																				var TEAM_USER : Bool;
																				var SYSTEM : Bool;
																				var BUGHUNTER_LEVEL_2 : Bool;
																				var VERIFIED_BOT : Bool;
																				var EARLY_VERIFIED_DEVELOPER : Bool;
																				var VERIFIED_DEVELOPER : Bool;
																			};
																			dynamic function toArray(hasParam:haxe.extern.Rest<Any>):Array<UserFlagsString>;
																			dynamic function toJSON():Float;
																			dynamic function valueOf():Float;
																		};
																		dynamic function has(bit:BitFieldResolvable<UserFlagsString>):Bool;
																		dynamic function missing(bits:BitFieldResolvable<UserFlagsString>, hasParam:haxe.extern.Rest<Any>):Array<UserFlagsString>;
																		dynamic function remove(bits:haxe.extern.Rest<BitFieldResolvable<UserFlagsString>>):BitField<UserFlagsString>;
																		dynamic function serialize(hasParam:haxe.extern.Rest<Any>):{
																			var DISCORD_EMPLOYEE : Bool;
																			var PARTNERED_SERVER_OWNER : Bool;
																			var DISCORD_PARTNER : Bool;
																			var HYPESQUAD_EVENTS : Bool;
																			var BUGHUNTER_LEVEL_1 : Bool;
																			var HOUSE_BRAVERY : Bool;
																			var HOUSE_BRILLIANCE : Bool;
																			var HOUSE_BALANCE : Bool;
																			var EARLY_SUPPORTER : Bool;
																			var TEAM_USER : Bool;
																			var SYSTEM : Bool;
																			var BUGHUNTER_LEVEL_2 : Bool;
																			var VERIFIED_BOT : Bool;
																			var EARLY_VERIFIED_DEVELOPER : Bool;
																			var VERIFIED_DEVELOPER : Bool;
																		};
																		dynamic function toArray(hasParam:haxe.extern.Rest<Any>):Array<UserFlagsString>;
																		dynamic function toJSON():Float;
																		dynamic function valueOf():Float;
																	};
																	dynamic function has(bit:BitFieldResolvable<UserFlagsString>):Bool;
																	dynamic function missing(bits:BitFieldResolvable<UserFlagsString>, hasParam:haxe.extern.Rest<Any>):Array<UserFlagsString>;
																	dynamic function remove(bits:haxe.extern.Rest<BitFieldResolvable<UserFlagsString>>):BitField<UserFlagsString>;
																	dynamic function serialize(hasParam:haxe.extern.Rest<Any>):{
																		var DISCORD_EMPLOYEE : Bool;
																		var PARTNERED_SERVER_OWNER : Bool;
																		var DISCORD_PARTNER : Bool;
																		var HYPESQUAD_EVENTS : Bool;
																		var BUGHUNTER_LEVEL_1 : Bool;
																		var HOUSE_BRAVERY : Bool;
																		var HOUSE_BRILLIANCE : Bool;
																		var HOUSE_BALANCE : Bool;
																		var EARLY_SUPPORTER : Bool;
																		var TEAM_USER : Bool;
																		var SYSTEM : Bool;
																		var BUGHUNTER_LEVEL_2 : Bool;
																		var VERIFIED_BOT : Bool;
																		var EARLY_VERIFIED_DEVELOPER : Bool;
																		var VERIFIED_DEVELOPER : Bool;
																	};
																	dynamic function toArray(hasParam:haxe.extern.Rest<Any>):Array<UserFlagsString>;
																	dynamic function toJSON():Float;
																	dynamic function valueOf():Float;
																};
																dynamic function has(bit:BitFieldResolvable<UserFlagsString>):Bool;
																dynamic function missing(bits:BitFieldResolvable<UserFlagsString>, hasParam:haxe.extern.Rest<Any>):Array<UserFlagsString>;
																dynamic function remove(bits:haxe.extern.Rest<BitFieldResolvable<UserFlagsString>>):BitField<UserFlagsString>;
																dynamic function serialize(hasParam:haxe.extern.Rest<Any>):{
																	var DISCORD_EMPLOYEE : Bool;
																	var PARTNERED_SERVER_OWNER : Bool;
																	var DISCORD_PARTNER : Bool;
																	var HYPESQUAD_EVENTS : Bool;
																	var BUGHUNTER_LEVEL_1 : Bool;
																	var HOUSE_BRAVERY : Bool;
																	var HOUSE_BRILLIANCE : Bool;
																	var HOUSE_BALANCE : Bool;
																	var EARLY_SUPPORTER : Bool;
																	var TEAM_USER : Bool;
																	var SYSTEM : Bool;
																	var BUGHUNTER_LEVEL_2 : Bool;
																	var VERIFIED_BOT : Bool;
																	var EARLY_VERIFIED_DEVELOPER : Bool;
																	var VERIFIED_DEVELOPER : Bool;
																};
																dynamic function toArray(hasParam:haxe.extern.Rest<Any>):Array<UserFlagsString>;
																dynamic function toJSON():Float;
																dynamic function valueOf():Float;
															};
															dynamic function has(bit:BitFieldResolvable<UserFlagsString>):Bool;
															dynamic function missing(bits:BitFieldResolvable<UserFlagsString>, hasParam:haxe.extern.Rest<Any>):Array<UserFlagsString>;
															dynamic function remove(bits:haxe.extern.Rest<BitFieldResolvable<UserFlagsString>>):BitField<UserFlagsString>;
															dynamic function serialize(hasParam:haxe.extern.Rest<Any>):{
																var DISCORD_EMPLOYEE : Bool;
																var PARTNERED_SERVER_OWNER : Bool;
																var DISCORD_PARTNER : Bool;
																var HYPESQUAD_EVENTS : Bool;
																var BUGHUNTER_LEVEL_1 : Bool;
																var HOUSE_BRAVERY : Bool;
																var HOUSE_BRILLIANCE : Bool;
																var HOUSE_BALANCE : Bool;
																var EARLY_SUPPORTER : Bool;
																var TEAM_USER : Bool;
																var SYSTEM : Bool;
																var BUGHUNTER_LEVEL_2 : Bool;
																var VERIFIED_BOT : Bool;
																var EARLY_VERIFIED_DEVELOPER : Bool;
																var VERIFIED_DEVELOPER : Bool;
															};
															dynamic function toArray(hasParam:haxe.extern.Rest<Any>):Array<UserFlagsString>;
															dynamic function toJSON():Float;
															dynamic function valueOf():Float;
														};
														dynamic function has(bit:BitFieldResolvable<UserFlagsString>):Bool;
														dynamic function missing(bits:BitFieldResolvable<UserFlagsString>, hasParam:haxe.extern.Rest<Any>):Array<UserFlagsString>;
														dynamic function remove(bits:haxe.extern.Rest<BitFieldResolvable<UserFlagsString>>):BitField<UserFlagsString>;
														dynamic function serialize(hasParam:haxe.extern.Rest<Any>):{
															var DISCORD_EMPLOYEE : Bool;
															var PARTNERED_SERVER_OWNER : Bool;
															var DISCORD_PARTNER : Bool;
															var HYPESQUAD_EVENTS : Bool;
															var BUGHUNTER_LEVEL_1 : Bool;
															var HOUSE_BRAVERY : Bool;
															var HOUSE_BRILLIANCE : Bool;
															var HOUSE_BALANCE : Bool;
															var EARLY_SUPPORTER : Bool;
															var TEAM_USER : Bool;
															var SYSTEM : Bool;
															var BUGHUNTER_LEVEL_2 : Bool;
															var VERIFIED_BOT : Bool;
															var EARLY_VERIFIED_DEVELOPER : Bool;
															var VERIFIED_DEVELOPER : Bool;
														};
														dynamic function toArray(hasParam:haxe.extern.Rest<Any>):Array<UserFlagsString>;
														dynamic function toJSON():Float;
														dynamic function valueOf():Float;
													};
													dynamic function has(bit:BitFieldResolvable<UserFlagsString>):Bool;
													dynamic function missing(bits:BitFieldResolvable<UserFlagsString>, hasParam:haxe.extern.Rest<Any>):Array<UserFlagsString>;
													dynamic function remove(bits:haxe.extern.Rest<BitFieldResolvable<UserFlagsString>>):BitField<UserFlagsString>;
													dynamic function serialize(hasParam:haxe.extern.Rest<Any>):{
														var DISCORD_EMPLOYEE : Bool;
														var PARTNERED_SERVER_OWNER : Bool;
														var DISCORD_PARTNER : Bool;
														var HYPESQUAD_EVENTS : Bool;
														var BUGHUNTER_LEVEL_1 : Bool;
														var HOUSE_BRAVERY : Bool;
														var HOUSE_BRILLIANCE : Bool;
														var HOUSE_BALANCE : Bool;
														var EARLY_SUPPORTER : Bool;
														var TEAM_USER : Bool;
														var SYSTEM : Bool;
														var BUGHUNTER_LEVEL_2 : Bool;
														var VERIFIED_BOT : Bool;
														var EARLY_VERIFIED_DEVELOPER : Bool;
														var VERIFIED_DEVELOPER : Bool;
													};
													dynamic function toArray(hasParam:haxe.extern.Rest<Any>):Array<UserFlagsString>;
													dynamic function toJSON():Float;
													dynamic function valueOf():Float;
												};
												dynamic function has(bit:BitFieldResolvable<UserFlagsString>):Bool;
												dynamic function missing(bits:BitFieldResolvable<UserFlagsString>, hasParam:haxe.extern.Rest<Any>):Array<UserFlagsString>;
												dynamic function remove(bits:haxe.extern.Rest<BitFieldResolvable<UserFlagsString>>):BitField<UserFlagsString>;
												dynamic function serialize(hasParam:haxe.extern.Rest<Any>):{
													var DISCORD_EMPLOYEE : Bool;
													var PARTNERED_SERVER_OWNER : Bool;
													var DISCORD_PARTNER : Bool;
													var HYPESQUAD_EVENTS : Bool;
													var BUGHUNTER_LEVEL_1 : Bool;
													var HOUSE_BRAVERY : Bool;
													var HOUSE_BRILLIANCE : Bool;
													var HOUSE_BALANCE : Bool;
													var EARLY_SUPPORTER : Bool;
													var TEAM_USER : Bool;
													var SYSTEM : Bool;
													var BUGHUNTER_LEVEL_2 : Bool;
													var VERIFIED_BOT : Bool;
													var EARLY_VERIFIED_DEVELOPER : Bool;
													var VERIFIED_DEVELOPER : Bool;
												};
												dynamic function toArray(hasParam:haxe.extern.Rest<Any>):Array<UserFlagsString>;
												dynamic function toJSON():Float;
												dynamic function valueOf():Float;
											};
											dynamic function has(bit:BitFieldResolvable<UserFlagsString>):Bool;
											dynamic function missing(bits:BitFieldResolvable<UserFlagsString>, hasParam:haxe.extern.Rest<Any>):Array<UserFlagsString>;
											dynamic function remove(bits:haxe.extern.Rest<BitFieldResolvable<UserFlagsString>>):BitField<UserFlagsString>;
											dynamic function serialize(hasParam:haxe.extern.Rest<Any>):{
												var DISCORD_EMPLOYEE : Bool;
												var PARTNERED_SERVER_OWNER : Bool;
												var DISCORD_PARTNER : Bool;
												var HYPESQUAD_EVENTS : Bool;
												var BUGHUNTER_LEVEL_1 : Bool;
												var HOUSE_BRAVERY : Bool;
												var HOUSE_BRILLIANCE : Bool;
												var HOUSE_BALANCE : Bool;
												var EARLY_SUPPORTER : Bool;
												var TEAM_USER : Bool;
												var SYSTEM : Bool;
												var BUGHUNTER_LEVEL_2 : Bool;
												var VERIFIED_BOT : Bool;
												var EARLY_VERIFIED_DEVELOPER : Bool;
												var VERIFIED_DEVELOPER : Bool;
											};
											dynamic function toArray(hasParam:haxe.extern.Rest<Any>):Array<UserFlagsString>;
											dynamic function toJSON():Float;
											dynamic function valueOf():Float;
										};
										dynamic function has(bit:BitFieldResolvable<UserFlagsString>):Bool;
										dynamic function missing(bits:BitFieldResolvable<UserFlagsString>, hasParam:haxe.extern.Rest<Any>):Array<UserFlagsString>;
										dynamic function remove(bits:haxe.extern.Rest<BitFieldResolvable<UserFlagsString>>):BitField<UserFlagsString>;
										dynamic function serialize(hasParam:haxe.extern.Rest<Any>):{
											var DISCORD_EMPLOYEE : Bool;
											var PARTNERED_SERVER_OWNER : Bool;
											var DISCORD_PARTNER : Bool;
											var HYPESQUAD_EVENTS : Bool;
											var BUGHUNTER_LEVEL_1 : Bool;
											var HOUSE_BRAVERY : Bool;
											var HOUSE_BRILLIANCE : Bool;
											var HOUSE_BALANCE : Bool;
											var EARLY_SUPPORTER : Bool;
											var TEAM_USER : Bool;
											var SYSTEM : Bool;
											var BUGHUNTER_LEVEL_2 : Bool;
											var VERIFIED_BOT : Bool;
											var EARLY_VERIFIED_DEVELOPER : Bool;
											var VERIFIED_DEVELOPER : Bool;
										};
										dynamic function toArray(hasParam:haxe.extern.Rest<Any>):Array<UserFlagsString>;
										dynamic function toJSON():Float;
										dynamic function valueOf():Float;
									};
									dynamic function has(bit:BitFieldResolvable<UserFlagsString>):Bool;
									dynamic function missing(bits:BitFieldResolvable<UserFlagsString>, hasParam:haxe.extern.Rest<Any>):Array<UserFlagsString>;
									dynamic function remove(bits:haxe.extern.Rest<BitFieldResolvable<UserFlagsString>>):BitField<UserFlagsString>;
									dynamic function serialize(hasParam:haxe.extern.Rest<Any>):{
										var DISCORD_EMPLOYEE : Bool;
										var PARTNERED_SERVER_OWNER : Bool;
										var DISCORD_PARTNER : Bool;
										var HYPESQUAD_EVENTS : Bool;
										var BUGHUNTER_LEVEL_1 : Bool;
										var HOUSE_BRAVERY : Bool;
										var HOUSE_BRILLIANCE : Bool;
										var HOUSE_BALANCE : Bool;
										var EARLY_SUPPORTER : Bool;
										var TEAM_USER : Bool;
										var SYSTEM : Bool;
										var BUGHUNTER_LEVEL_2 : Bool;
										var VERIFIED_BOT : Bool;
										var EARLY_VERIFIED_DEVELOPER : Bool;
										var VERIFIED_DEVELOPER : Bool;
									};
									dynamic function toArray(hasParam:haxe.extern.Rest<Any>):Array<UserFlagsString>;
									dynamic function toJSON():Float;
									dynamic function valueOf():Float;
								};
								dynamic function has(bit:BitFieldResolvable<UserFlagsString>):Bool;
								dynamic function missing(bits:BitFieldResolvable<UserFlagsString>, hasParam:haxe.extern.Rest<Any>):Array<UserFlagsString>;
								dynamic function remove(bits:haxe.extern.Rest<BitFieldResolvable<UserFlagsString>>):BitField<UserFlagsString>;
								dynamic function serialize(hasParam:haxe.extern.Rest<Any>):{
									var DISCORD_EMPLOYEE : Bool;
									var PARTNERED_SERVER_OWNER : Bool;
									var DISCORD_PARTNER : Bool;
									var HYPESQUAD_EVENTS : Bool;
									var BUGHUNTER_LEVEL_1 : Bool;
									var HOUSE_BRAVERY : Bool;
									var HOUSE_BRILLIANCE : Bool;
									var HOUSE_BALANCE : Bool;
									var EARLY_SUPPORTER : Bool;
									var TEAM_USER : Bool;
									var SYSTEM : Bool;
									var BUGHUNTER_LEVEL_2 : Bool;
									var VERIFIED_BOT : Bool;
									var EARLY_VERIFIED_DEVELOPER : Bool;
									var VERIFIED_DEVELOPER : Bool;
								};
								dynamic function toArray(hasParam:haxe.extern.Rest<Any>):Array<UserFlagsString>;
								dynamic function toJSON():Float;
								dynamic function valueOf():Float;
							};
							dynamic function has(bit:BitFieldResolvable<UserFlagsString>):Bool;
							dynamic function missing(bits:BitFieldResolvable<UserFlagsString>, hasParam:haxe.extern.Rest<Any>):Array<UserFlagsString>;
							dynamic function remove(bits:haxe.extern.Rest<BitFieldResolvable<UserFlagsString>>):BitField<UserFlagsString>;
							dynamic function serialize(hasParam:haxe.extern.Rest<Any>):{
								var DISCORD_EMPLOYEE : Bool;
								var PARTNERED_SERVER_OWNER : Bool;
								var DISCORD_PARTNER : Bool;
								var HYPESQUAD_EVENTS : Bool;
								var BUGHUNTER_LEVEL_1 : Bool;
								var HOUSE_BRAVERY : Bool;
								var HOUSE_BRILLIANCE : Bool;
								var HOUSE_BALANCE : Bool;
								var EARLY_SUPPORTER : Bool;
								var TEAM_USER : Bool;
								var SYSTEM : Bool;
								var BUGHUNTER_LEVEL_2 : Bool;
								var VERIFIED_BOT : Bool;
								var EARLY_VERIFIED_DEVELOPER : Bool;
								var VERIFIED_DEVELOPER : Bool;
							};
							dynamic function toArray(hasParam:haxe.extern.Rest<Any>):Array<UserFlagsString>;
							dynamic function toJSON():Float;
							dynamic function valueOf():Float;
						};
						dynamic function has(bit:BitFieldResolvable<UserFlagsString>):Bool;
						dynamic function missing(bits:BitFieldResolvable<UserFlagsString>, hasParam:haxe.extern.Rest<Any>):Array<UserFlagsString>;
						dynamic function remove(bits:haxe.extern.Rest<BitFieldResolvable<UserFlagsString>>):BitField<UserFlagsString>;
						dynamic function serialize(hasParam:haxe.extern.Rest<Any>):{
							var DISCORD_EMPLOYEE : Bool;
							var PARTNERED_SERVER_OWNER : Bool;
							var DISCORD_PARTNER : Bool;
							var HYPESQUAD_EVENTS : Bool;
							var BUGHUNTER_LEVEL_1 : Bool;
							var HOUSE_BRAVERY : Bool;
							var HOUSE_BRILLIANCE : Bool;
							var HOUSE_BALANCE : Bool;
							var EARLY_SUPPORTER : Bool;
							var TEAM_USER : Bool;
							var SYSTEM : Bool;
							var BUGHUNTER_LEVEL_2 : Bool;
							var VERIFIED_BOT : Bool;
							var EARLY_VERIFIED_DEVELOPER : Bool;
							var VERIFIED_DEVELOPER : Bool;
						};
						dynamic function toArray(hasParam:haxe.extern.Rest<Any>):Array<UserFlagsString>;
						dynamic function toJSON():Float;
						dynamic function valueOf():Float;
					};
					dynamic function has(bit:BitFieldResolvable<UserFlagsString>):Bool;
					dynamic function missing(bits:BitFieldResolvable<UserFlagsString>, hasParam:haxe.extern.Rest<Any>):Array<UserFlagsString>;
					dynamic function remove(bits:haxe.extern.Rest<BitFieldResolvable<UserFlagsString>>):BitField<UserFlagsString>;
					dynamic function serialize(hasParam:haxe.extern.Rest<Any>):{
						var DISCORD_EMPLOYEE : Bool;
						var PARTNERED_SERVER_OWNER : Bool;
						var DISCORD_PARTNER : Bool;
						var HYPESQUAD_EVENTS : Bool;
						var BUGHUNTER_LEVEL_1 : Bool;
						var HOUSE_BRAVERY : Bool;
						var HOUSE_BRILLIANCE : Bool;
						var HOUSE_BALANCE : Bool;
						var EARLY_SUPPORTER : Bool;
						var TEAM_USER : Bool;
						var SYSTEM : Bool;
						var BUGHUNTER_LEVEL_2 : Bool;
						var VERIFIED_BOT : Bool;
						var EARLY_VERIFIED_DEVELOPER : Bool;
						var VERIFIED_DEVELOPER : Bool;
					};
					dynamic function toArray(hasParam:haxe.extern.Rest<Any>):Array<UserFlagsString>;
					dynamic function toJSON():Float;
					dynamic function valueOf():Float;
				};
				dynamic function has(bit:BitFieldResolvable<UserFlagsString>):Bool;
				dynamic function missing(bits:BitFieldResolvable<UserFlagsString>, hasParam:haxe.extern.Rest<Any>):Array<UserFlagsString>;
				dynamic function remove(bits:haxe.extern.Rest<BitFieldResolvable<UserFlagsString>>):BitField<UserFlagsString>;
				dynamic function serialize(hasParam:haxe.extern.Rest<Any>):{
					var DISCORD_EMPLOYEE : Bool;
					var PARTNERED_SERVER_OWNER : Bool;
					var DISCORD_PARTNER : Bool;
					var HYPESQUAD_EVENTS : Bool;
					var BUGHUNTER_LEVEL_1 : Bool;
					var HOUSE_BRAVERY : Bool;
					var HOUSE_BRILLIANCE : Bool;
					var HOUSE_BALANCE : Bool;
					var EARLY_SUPPORTER : Bool;
					var TEAM_USER : Bool;
					var SYSTEM : Bool;
					var BUGHUNTER_LEVEL_2 : Bool;
					var VERIFIED_BOT : Bool;
					var EARLY_VERIFIED_DEVELOPER : Bool;
					var VERIFIED_DEVELOPER : Bool;
				};
				dynamic function toArray(hasParam:haxe.extern.Rest<Any>):Array<UserFlagsString>;
				dynamic function toJSON():Float;
				dynamic function valueOf():Float;
			};
			dynamic function has(bit:BitFieldResolvable<UserFlagsString>):Bool;
			dynamic function missing(bits:BitFieldResolvable<UserFlagsString>, hasParam:haxe.extern.Rest<Any>):Array<UserFlagsString>;
			dynamic function remove(bits:haxe.extern.Rest<BitFieldResolvable<UserFlagsString>>):BitField<UserFlagsString>;
			dynamic function serialize(hasParam:haxe.extern.Rest<Any>):{
				var DISCORD_EMPLOYEE : Bool;
				var PARTNERED_SERVER_OWNER : Bool;
				var DISCORD_PARTNER : Bool;
				var HYPESQUAD_EVENTS : Bool;
				var BUGHUNTER_LEVEL_1 : Bool;
				var HOUSE_BRAVERY : Bool;
				var HOUSE_BRILLIANCE : Bool;
				var HOUSE_BALANCE : Bool;
				var EARLY_SUPPORTER : Bool;
				var TEAM_USER : Bool;
				var SYSTEM : Bool;
				var BUGHUNTER_LEVEL_2 : Bool;
				var VERIFIED_BOT : Bool;
				var EARLY_VERIFIED_DEVELOPER : Bool;
				var VERIFIED_DEVELOPER : Bool;
			};
			dynamic function toArray(hasParam:haxe.extern.Rest<Any>):Array<UserFlagsString>;
			dynamic function toJSON():Float;
			dynamic function valueOf():Float;
		};
		dynamic function has(bit:BitFieldResolvable<UserFlagsString>):Bool;
		dynamic function missing(bits:BitFieldResolvable<UserFlagsString>, hasParam:haxe.extern.Rest<Any>):Array<UserFlagsString>;
		dynamic function remove(bits:haxe.extern.Rest<BitFieldResolvable<UserFlagsString>>):BitField<UserFlagsString>;
		dynamic function serialize(hasParam:haxe.extern.Rest<Any>):{
			var DISCORD_EMPLOYEE : Bool;
			var PARTNERED_SERVER_OWNER : Bool;
			var DISCORD_PARTNER : Bool;
			var HYPESQUAD_EVENTS : Bool;
			var BUGHUNTER_LEVEL_1 : Bool;
			var HOUSE_BRAVERY : Bool;
			var HOUSE_BRILLIANCE : Bool;
			var HOUSE_BALANCE : Bool;
			var EARLY_SUPPORTER : Bool;
			var TEAM_USER : Bool;
			var SYSTEM : Bool;
			var BUGHUNTER_LEVEL_2 : Bool;
			var VERIFIED_BOT : Bool;
			var EARLY_VERIFIED_DEVELOPER : Bool;
			var VERIFIED_DEVELOPER : Bool;
		};
		dynamic function toArray(hasParam:haxe.extern.Rest<Any>):Array<UserFlagsString>;
		dynamic function toJSON():Float;
		dynamic function valueOf():Float;
	}>;
	var locale : Null<String>;
	var system : Null<Bool>;
	final tag : Dynamic;
	var username : Dynamic;
	var lastMessageID : Null<String>;
	var lastMessage : Null<Message>;
	@:overload(function(options:Dynamic):js.lib.Promise<Array<Message>> { })
	@:overload(function(options:ts.AnyOf2<APIMessage, MessageOptions>):js.lib.Promise<ts.AnyOf2<Message, Array<Message>>> { })
	@:overload(function(content:Dynamic, options:ts.AnyOf4<MessageEmbed, MessageAttachment, Array<ts.AnyOf2<MessageEmbed, MessageAttachment>>, Dynamic>):js.lib.Promise<Message> { })
	@:overload(function(content:Dynamic, options:Dynamic):js.lib.Promise<Array<Message>> { })
	@:overload(function(content:Dynamic, options:MessageOptions):js.lib.Promise<ts.AnyOf2<Message, Array<Message>>> { })
	dynamic function send(content:ts.AnyOf10<String, Float, { }, Bool, js.lib.Symbol, MessageEmbed, MessageAttachment, Array<ts.AnyOf2<MessageEmbed, MessageAttachment>>, haxe.ds.ReadOnlyArray<Dynamic>, Dynamic>):js.lib.Promise<Message>;
	dynamic function equals(user:User):Bool;
	dynamic function toJSON(props:haxe.extern.Rest<{ }>):Dynamic;
	/**
		Returns the primitive value of the specified object.
	**/
	@:overload(function():String { })
	dynamic function valueOf():Dynamic;
	var client : Client;
	var createdAt : js.lib.Date;
	var createdTimestamp : Float;
	var id : String;
	var partial : Bool;
	dynamic function fetch():js.lib.Promise<User>;
	/**
		Returns a string representation of an object.
	**/
	dynamic function toString():String;
	var avatar : Null<String>;
	var discriminator : Null<String>;
	var defaultAvatarURL : Null<String>;
	var dmChannel : Null<DMChannel>;
	var presence : Null<Presence>;
	dynamic function avatarURL(?options:ImageURLOptions & { @:optional @:native("dynamic") var dynamic_ : Bool; }):Null<String>;
	dynamic function createDM():js.lib.Promise<DMChannel>;
	dynamic function deleteDM():js.lib.Promise<DMChannel>;
	dynamic function displayAvatarURL(?options:ImageURLOptions & { @:optional @:native("dynamic") var dynamic_ : Bool; }):String;
	dynamic function fetchFlags(?force:Bool):js.lib.Promise<UserFlags>;
	dynamic function typingDurationIn(channel:ChannelResolvable):Float;
	dynamic function typingIn(channel:ChannelResolvable):Bool;
	dynamic function typingSinceIn(channel:ChannelResolvable):js.lib.Date;
};